const centralniDatabaze = {
    barvy: [
        { cesky: "červená", en: "red", de: "rot", es: "rojo", nl: "rood", fr: "rouge", sv: "röd", ru: "красный", it: "rosso" },
        { cesky: "modrá", en: "blue", de: "blau", es: "azul", nl: "blauw", fr: "bleu", sv: "blå", ru: "синий", it: "blu" },
        { cesky: "zelená", en: "green", de: "grün", es: "verde", nl: "groen", fr: "vert", sv: "grön", ru: "зеленый", it: "verde" },
        { cesky: "žlutá", en: "yellow", de: "gelb", es: "amarillo", nl: "geel", fr: "jaune", sv: "gul", ru: "желтый", it: "giallo" },
        { cesky: "černá", en: "black", de: "schwarz", es: "negro", nl: "zwart", fr: "noir", sv: "svart", ru: "черный", it: "nero" },
        { cesky: "bílá", en: "white", de: "weiß", es: "blanco", nl: "wit", fr: "blanc", sv: "vit", ru: "белый", it: "bianco" },
        { cesky: "oranžová", en: "orange", de: "orange", es: "naranja", nl: "oranje", fr: "orange", sv: "orange", ru: "оранжевый", it: "arancione" },
        { cesky: "růžová", en: "pink", de: "rosa", es: "rosa", nl: "roze", fr: "rose", sv: "rosa", ru: "розовый", it: "rosa" },
        { cesky: "šedá", en: "grey", de: "grau", es: "gris", nl: "grijs", fr: "gris", sv: "grå", ru: "серый", it: "grigio" }
    ],
    cisla: [
        { cesky: "jedna", en: "one", de: "eins", es: "uno", nl: "één", fr: "un", sv: "ett", ru: "один", it: "uno" },
        { cesky: "dva", en: "two", de: "zwei", es: "dos", nl: "twee", fr: "deux", sv: "två", ru: "два", it: "due" },
        { cesky: "tři", en: "three", de: "drei", es: "tres", nl: "drie", fr: "trois", sv: "tre", ru: "три", it: "tre" },
        { cesky: "čtyři", en: "four", de: "vier", es: "cuatro", nl: "vier", fr: "quatre", sv: "fyra", ru: "четыре", it: "quattro" },
        { cesky: "pět", en: "five", de: "fünf", es: "cinco", nl: "vijf", fr: "cinq", sv: "fem", ru: "пять", it: "cinque" },
        { cesky: "šest", en: "six", de: "sechs", es: "seis", nl: "zes", fr: "six", sv: "sex", ru: "шесть", it: "sei" },
        { cesky: "sedm", en: "seven", de: "sieben", es: "siete", nl: "zeven", fr: "sept", sv: "sju", ru: "семь", it: "sette" },
        { cesky: "osm", en: "eight", de: "acht", es: "ocho", nl: "acht", fr: "huit", sv: "åtta", ru: "восемь", it: "otto" },
        { cesky: "devět", en: "nine", de: "neun", es: "nueve", nl: "negen", fr: "neuf", sv: "nio", ru: "девать", it: "nove" },
        { cesky: "deset", en: "ten", de: "zehn", es: "diez", nl: "tien", fr: "dix", sv: "tio", ru: "десять", it: "dieci" },
        { cesky: "jedenáct", en: "eleven", de: "elf", es: "once", nl: "elf", fr: "onze", sv: "elva", ru: "одиннадцать", it: "undici" },
        { cesky: "dvanáct", en: "twelve", de: "zwölf", es: "doce", nl: "twaalf", fr: "douze", sv: "tolv", ru: "двенадцать", it: "dodici" },
        { cesky: "třináct", en: "thirteen", de: "dreizehn", es: "trece", nl: "dertien", fr: "treize", sv: "tretton", ru: "тринадцать", it: "tredici" },
        { cesky: "čtrnáct", en: "fourteen", de: "vierzehn", es: "catorce", nl: "veertien", fr: "quatorze", sv: "fjorton", ru: "четырнадцать", it: "quattordici" },
        { cesky: "patnáct", en: "fifteen", de: "fünfzehn", es: "quince", nl: "vijftien", fr: "quinze", sv: "femton", ru: "пятнадцать", it: "quindici" },
        { cesky: "šestnáct", en: "sixteen", de: "sechzehn", es: "diecisiete", nl: "zestien", fr: "seize", sv: "sexton", ru: "шестнадцать", it: "sedici" },
        { cesky: "sedmnáct", en: "seventeen", de: "siebzehn", es: "diecisiete", nl: "zeventien", fr: "dix-sept", sv: "sjutton", ru: "семнадцать", it: "diciassette" },
        { cesky: "osmnáct", en: "eighteen", de: "achtzehn", es: "dieciocho", nl: "achtien", fr: "dix-huit", sv: "arton", ru: "восемнадцать", it: "diciotto" },
        { cesky: "devatenáct", en: "nineteen", de: "neunzehn", es: "diecinueve", nl: "negentien", fr: "dix-neuf", sv: "nitton", ru: "девятнадцать", it: "diciannove" },
        { cesky: "dvacet", en: "twenty", de: "zwanzig", es: "veinte", nl: "twintig", fr: "vingt", sv: "tjugo", ru: "двадцать", it: "venti" },
        { cesky: "sto", en: "hundred", de: "hundert", es: "cien", nl: "honderd", fr: "cent", sv: "hundra", ru: "сто", it: "cento" },
        { cesky: "tisíc", en: "thousand", de: "tausend", es: "mil", nl: "duizend", fr: "mille", sv: "tusen", ru: "тысяча", it: "mille" }
    ],
    dny_v_tydnu: [
        { cesky: "pondělí", en: "monday", de: "montag", es: "lunes", nl: "maandag", fr: "lundi", sv: "måndag", ru: "понедельник", it: "lunedì" },
        { cesky: "úterý", en: "tuesday", de: "dienstag", es: "martes", nl: "dinsdag", fr: "mardi", sv: "tisdag", ru: "вторник", it: "martedì" },
        { cesky: "středa", en: "wednesday", de: "mittwoch", es: "miércoles", nl: "woensdag", fr: "mercredi", sv: "onsdag", ru: "среда", it: "mercoledì" },
        { cesky: "čtvrtek", en: "thursday", de: "donnerstag", es: "jueves", nl: "donderdag", fr: "jeudi", sv: "torsdag", ru: "четверг", it: "giovedì" },
        { cesky: "pátek", en: "friday", de: "freitag", es: "viernes", nl: "vrijdag", fr: "vendredi", sv: "fredag", ru: "пятница", it: "venerdì" },
        { cesky: "sobota", en: "saturday", de: "samstag", es: "sábado", nl: "zaterdag", fr: "samedi", sv: "lördag", ru: "суббота", it: "sabato" },
        { cesky: "neděle", en: "sunday", de: "sonntag", es: "domingo", nl: "zondag", fr: "dimanche", sv: "söndag", ru: "воскресенье", it: "domenica" }
    ],
    mesice: [
        { cesky: "leden", en: "january", de: "januar", es: "enero", nl: "januari", fr: "janvier", sv: "januari", ru: "январь", it: "gennaio" },
        { cesky: "únor", en: "february", de: "februar", es: "febrero", nl: "februari", fr: "février", sv: "februari", ru: "февраль", it: "febbraio" },
        { cesky: "březen", en: "march", de: "märz", es: "marzo", nl: "maart", fr: "mars", sv: "mars", ru: "март", it: "marzo" },
        { cesky: "duben", en: "april", de: "april", es: "abril", nl: "april", fr: "avril", sv: "april", ru: "апрель", it: "aprile" },
        { cesky: "květen", en: "may", de: "mai", es: "mayo", nl: "mei", fr: "mai", sv: "maj", ru: "май", it: "maggio" },
        { cesky: "červen", en: "june", de: "juni", es: "junio", nl: "juni", fr: "juin", sv: "juni", ru: "июнь", it: "giugno" },
        { cesky: "červenec", en: "july", de: "juli", es: "julio", nl: "juli", fr: "juillet", sv: "juli", ru: "июль", it: "luglio" },
        { cesky: "srpen", en: "august", de: "august", es: "agosto", nl: "augustus", fr: "août", sv: "augusti", ru: "август", it: "agosto" },
        { cesky: "září", en: "september", de: "september", es: "septiembre", nl: "september", fr: "septembre", sv: "september", ru: "сентябрь", it: "settembre" },
        { cesky: "říjen", en: "october", de: "oktober", es: "octubre", nl: "oktober", fr: "octobre", sv: "oktober", ru: "октябрь", it: "ottobre" },
        { cesky: "listopad", en: "november", de: "november", es: "noviembre", nl: "november", fr: "novembre", sv: "november", ru: "ноябрь", it: "novembre" },
        { cesky: "prosinec", en: "december", de: "dezember", es: "diciembre", nl: "december", fr: "décembre", sv: "december", ru: "декабрь", it: "dicembre" }
    ],
    zakladni_fraze: [
        { cesky: "ahoj", en: "hello", de: "hallo", es: "hola", nl: "hallo", fr: "salut", sv: "hej", ru: "привет", it: "ciao" },
        { cesky: "dobré ráno", en: "good morning", de: "guten morgen", es: "buenos días", nl: "goedemorgen", fr: "bonjour", sv: "god morgon", ru: "доброе утро", it: "buongiorno" },
        { cesky: "dobrý den", en: "good afternoon", de: "guten tag", es: "buenas tardes", nl: "goedendag", fr: "bonjour", sv: "god dag", ru: "добрый день", it: "buongiorno" },
        { cesky: "dobrou noc", en: "good night", de: "gute nacht", es: "buenas noches", nl: "goedenacht", fr: "bonne nuit", sv: "god natt", ru: "спокойной ночи", it: "buonanotte" },
        { cesky: "na shledanou", en: "goodbye", de: "auf wiedersehen", es: "adiós", nl: "tot ziens", fr: "au revoir", sv: "hej då", ru: "до свидания", it: "arrivederci" },
        { cesky: "prosím", en: "please", de: "bitte", es: "por favor", nl: "alstublieft", fr: "s'il vous plaît", sv: "snälla", ru: "пожалуйста", it: "per favore" },
        { cesky: "děkuji", en: "thank you", de: "danke", es: "gracias", nl: "dank u", fr: "merci", sv: "tack", ru: "спасибо", it: "grazie" },
        { cesky: "promiňte", en: "excuse me", de: "entschuldigung", es: "disculpe", nl: "pardon", fr: "excusez-moi", sv: "ursäkta", ru: "извините", it: "scusa" },
        { cesky: "jak se máš", en: "how are you", de: "wie geht es dir", es: "cómo estás", nl: "hoe gaat het", fr: "comment ça va", sv: "hur mår du", ru: "как дела", it: "come stai" },
        { cesky: "ano", en: "yes", de: "ja", es: "sí", nl: "ja", fr: "oui", sv: "ja", ru: "да", it: "sì" }
    ],
    rodina: [
        { cesky: "matka", en: "mother", de: "mutter", es: "madre", nl: "moeder", fr: "mère", sv: "mamma", ru: "мать", it: "madre" },
        { cesky: "otec", en: "father", de: "vater", es: "padre", nl: "vader", fr: "père", sv: "pappa", ru: "отец", it: "padre" },
        { cesky: "syn", en: "son", de: "sohn", es: "hijo", nl: "zoon", fr: "fils", sv: "son", ru: "сын", it: "figlio" },
        { cesky: "dcera", en: "daughter", de: "tochter", es: "hija", nl: "dochter", fr: "fille", sv: "dotter", ru: "дочь", it: "figlia" },
        { cesky: "dědeček", en: "grandfather", de: "großvater", es: "abuelo", nl: "grootvader", fr: "grand-père", sv: "morfar", ru: "дедушка", it: "nonno" },
        { cesky: "babička", en: "grandmother", de: "großmutter", es: "abuela", nl: "grootmoeder", fr: "grand-mère", sv: "mormor", ru: "бабушка", it: "nonna" },
        { cesky: "teta", en: "aunt", de: "tante", es: "tía", nl: "tante", fr: "tante", sv: "faster", ru: "тетя", it: "zia" },
        { cesky: "strýc", en: "uncle", de: "onkel", es: "tío", nl: "oom", fr: "oncle", sv: "farbror", ru: "дядя", it: "zio" },
        { cesky: "vnuk", en: "grandson", de: "enkel", es: "nieto", nl: "kleinzoon", fr: "petit-fils", sv: "barnbarn", ru: "внук", it: "nipote" },
        { cesky: "vnučka", en: "granddaughter", de: "enkelin", es: "nieta", nl: "kleindochter", fr: "petite-fille", sv: "barnbarn", ru: "внучка", it: "nipote" },
        { cesky: "bratr", en: "brother", de: "bruder", es: "hermano", nl: "broer", fr: "frère", sv: "bror", ru: "брат", it: "fratello" },
        { cesky: "sestra", en: "sister", de: "schwester", es: "hermana", nl: "zus", fr: "sœur", sv: "syster", ru: "сестра", it: "sorella" },
        { cesky: "sourozenec", en: "sibling", de: "geschwister", es: "hermano", nl: "broer of zus", fr: "frère ou sœur", sv: "syskon", ru: "родной брат", it: "fratello" }
    ],
    casti_tela: [
        { cesky: "hlava", en: "head", de: "kopf", es: "cabeza", nl: "hoofd", fr: "tête", sv: "huvud", ru: "голова", it: "testa" },
        { cesky: "oko", en: "eye", de: "auge", es: "ojo", nl: "oog", fr: "œil", sv: "öga", ru: "глаз", it: "occhio" },
        { cesky: "ucho", en: "ear", de: "ohr", es: "oreja", nl: "oor", fr: "oreille", sv: "öra", ru: "ухо", it: "orecchio" },
        { cesky: "nos", en: "nose", de: "nase", es: "nariz", nl: "neus", fr: "nez", sv: "näsa", ru: "нос", it: "naso" },
        { cesky: "ústa", en: "mouth", de: "mund", es: "boca", nl: "mond", fr: "bouche", sv: "mun", ru: "рот", it: "bocca" },
        { cesky: "ruka", en: "hand", de: "hand", es: "mano", nl: "hand", fr: "main", sv: "hand", ru: "рука", it: "mano" },
        { cesky: "noha", en: "leg", de: "bein", es: "pierna", nl: "been", fr: "jambe", sv: "ben", ru: "нога", it: "gamba" },
        { cesky: "paže", en: "arm", de: "arm", es: "brazo", nl: "arm", fr: "bras", sv: "arm", ru: "рука", it: "braccio" },
        { cesky: "chodidlo", en: "foot", de: "fuß", es: "pie", nl: "voet", fr: "pied", sv: "fot", ru: "стопа", it: "piede" },
        { cesky: "prst", en: "finger", de: "finger", es: "dedo", nl: "vinger", fr: "doigt", sv: "finger", ru: "палец", it: "dito" }
    ],
    vlastnosti_tela: [
        { cesky: "malý", en: "small", de: "klein", es: "pequeño", nl: "klein", fr: "petit", sv: "liten", ru: "маленький", it: "piccolo" },
        { cesky: "velký", en: "big", de: "groß", es: "grande", nl: "groot", fr: "grand", sv: "stor", ru: "большой", it: "grande" },
        { cesky: "dlouhý", en: "long", de: "lang", es: "largo", nl: "lang", fr: "long", sv: "lång", ru: "длинный", it: "lungo" },
        { cesky: "tlustý", en: "fat", de: "dick", es: "gordo", nl: "dik", fr: "gros", sv: "tjock", ru: "толстый", it: "grasso" },
        { cesky: "štíhlý", en: "slim", de: "schlank", es: "delgado", nl: "slank", fr: "mince", sv: "smal", ru: "стройный", it: "snello" },
        { cesky: "plešatý", en: "bald", de: "glatzköpfig", es: "calvo", nl: "kaal", fr: "chauve", sv: "skallig", ru: "лысый", it: "calvo" },
        { cesky: "mladý", en: "young", de: "jung", es: "joven", nl: "jong", fr: "jeune", sv: "ung", ru: "молодой", it: "giovane" },
        { cesky: "starý", en: "old", de: "alt", es: "viejo", nl: "oud", fr: "vieux", sv: "gammal", ru: "старый", it: "vecchio" }
    ],
    mistnosti_v_dome: [
        { cesky: "pokoj", en: "room", de: "zimmer", es: "habitación", nl: "kamer", fr: "chambre", sv: "rum", ru: "комната", it: "stanza" },
        { cesky: "záchod", en: "toilet", de: "toilette", es: "váter", nl: "toilet", fr: "toilette", sv: "toalett", ru: "туалет", it: "water" },
        { cesky: "koupelna", en: "bathroom", de: "badezimmer", es: "baño", nl: "badkamer", fr: "salle de bain", sv: "badrum", ru: "ванная", it: "bagno" },
        { cesky: "kuchyně", en: "kitchen", de: "küche", es: "cocina", nl: "keuken", fr: "cuisine", sv: "kök", ru: "кухня", it: "cucina" },
        { cesky: "předsíň", en: "hallway", de: "diele", es: "recibidor", nl: "hal", fr: "entrée", sv: "hall", ru: "прихожая", it: "ingresso" },
        { cesky: "garáž", en: "garage", de: "garage", es: "garaje", nl: "garage", fr: "garage", sv: "garage", ru: "гараж", it: "garage" },
        { cesky: "chodba", en: "corridor", de: "flur", es: "pasillo", nl: "gang", fr: "couloir", sv: "korridor", ru: "коридор", it: "corridoio" },
        { cesky: "sklep", en: "cellar", de: "keller", es: "sótano", nl: "kelder", fr: "cave", sv: "källare", ru: "подвал", it: "cantina" },
        { cesky: "obývák", en: "living room", de: "wohnzimmer", es: "salón", nl: "woonkamer", fr: "salon", sv: "vardagsrum", ru: "гостиная", it: "salotto" },
        { cesky: "jídelna", en: "dining room", de: "esszimmer", es: "comedor", nl: "eetkamer", fr: "salle à manger", sv: "matsal", ru: "столовая", it: "sala da pranzo" }
    ],
    zakladni_budovy: [
        { cesky: "škola", en: "school", de: "schule", es: "escuela", nl: "school", fr: "école", sv: "skola", ru: "школа", it: "scuola" },
        { cesky: "nemocnice", en: "hospital", de: "krankenhaus", es: "hospital", nl: "ziekenhuis", fr: "hôpital", sv: "sjukhus", ru: "больница", it: "ospedale" },
        { cesky: "nádraží", en: "station", de: "bahnhof", es: "estación", nl: "station", fr: "gare", sv: "station", ru: "вокзал", it: "stazione" },
        { cesky: "radnice", en: "town hall", de: "rathaus", es: "ayuntamiento", nl: "stadhuis", fr: "mairie", sv: "stadshus", ru: "ратуша", it: "municipio" },
        { cesky: "letiště", en: "airport", de: "flughafen", es: "aeropuerto", nl: "luchthaven", fr: "aéroport", sv: "flygplats", ru: "аэропорт", it: "aeroporto" },
        { cesky: "divadlo", en: "theatre", de: "theater", es: "teatro", nl: "theater", fr: "théâtre", sv: "teater", ru: "театр", it: "teatro" },
        { cesky: "kino", en: "cinema", de: "kino", es: "cine", nl: "bioscoop", fr: "cinéma", sv: "bio", ru: "кинотеатр", it: "cinema" },
        { cesky: "náměstí", en: "square", de: "platz", es: "plaza", nl: "plein", fr: "place", sv: "torg", ru: "площадь", it: "piazza" },
        { cesky: "obchod", en: "shop", de: "geschäft", es: "tienda", nl: "winkel", fr: "magasin", sv: "affär", ru: "магазин", it: "negozio" }
    ],
    pocasi: [
        { cesky: "slunce", en: "sun", de: "sonne", es: "sol", nl: "zon", fr: "soleil", sv: "sol", ru: "солнце", it: "sole" },
        { cesky: "déšť", en: "rain", de: "regen", es: "lluvia", nl: "regen", fr: "pluie", sv: "regn", ru: "дождь", it: "pioggia" },
        { cesky: "zataženo", en: "cloudy", de: "bewölkt", es: "nublado", nl: "bewolkt", fr: "nuageux", sv: "molnigt", ru: "облачно", it: "nuvoloso" },
        { cesky: "sníh", en: "snow", de: "schnee", es: "nieve", nl: "sneeuw", fr: "neige", sv: "snö", ru: "снег", it: "neve" },
        { cesky: "vítr", en: "wind", de: "wind", es: "viento", nl: "wind", fr: "vent", sv: "vind", ru: "ветер", it: "vento" },
        { cesky: "bouřka", en: "storm", de: "gewitter", es: "tormenta", nl: "storm", fr: "orage", sv: "storm", ru: "гроза", it: "tempesta" },
        { cesky: "zima", en: "cold", de: "kälte", es: "frío", nl: "koude", fr: "froid", sv: "kyla", ru: "холод", it: "freddo" },
        { cesky: "teplo", en: "warm", de: "wärme", es: "calor", nl: "warmte", fr: "chaud", sv: "värme", ru: "тепло", it: "caldo" },
        { cesky: "horko", en: "hot", de: "hitze", es: "caluroso", nl: "heet", fr: "brûlant", sv: "hetta", ru: "жара", it: "caldo" },
        { cesky: "chladno", en: "chilly", de: "kühl", es: "fresco", nl: "fris", fr: "frais", sv: "kylig", ru: "прохладно", it: "fresco" }
    ],
    konicky_a_sporty: [
        { cesky: "fotbal", en: "football", de: "fußball", es: "fútbol", nl: "voetbal", fr: "football", sv: "fotboll", ru: "футбол", it: "calcio" },
        { cesky: "tenis", en: "tennis", de: "tennis", es: "tenis", nl: "tennis", fr: "tennis", sv: "tennis", ru: "теннис", it: "tennis" },
        { cesky: "plavání", en: "swimming", de: "schwimmen", es: "natación", nl: "zwemmen", fr: "natation", sv: "simning", ru: "плавание", it: "nuoto" },
        { cesky: "běh", en: "running", de: "laufen", es: "carrera", nl: "hardlopen", fr: "courir", sv: "löpning", ru: "бег", it: "corsa" },
        { cesky: "cyklistika", en: "cycling", de: "radfahren", es: "ciclismo", nl: "fietsen", fr: "cyclisme", sv: "cykling", ru: "велоспорт", it: "ciclismo" },
        { cesky: "muzika", en: "music", de: "musik", es: "música", nl: "muziek", fr: "musique", sv: "musik", ru: "музыка", it: "musica" },
        { cesky: "filmy", en: "movies", de: "filme", es: "películas", nl: "films", fr: "films", sv: "filmer", ru: "фильмы", it: "film" },
        { cesky: "čtení", en: "reading", de: "lesen", es: "lectura", nl: "lezen", fr: "lecture", sv: "läsning", ru: "чтение", it: "lettura" }
    ],
    dopravni_prostredky: [
        { cesky: "auto", en: "car", de: "auto", es: "coche", nl: "auto", fr: "voiture", sv: "bil", ru: "машина", it: "automobile" },
        { cesky: "autobus", en: "bus", de: "bus", es: "autobús", nl: "bus", fr: "bus", sv: "buss", ru: "автобус", it: "autobus" },
        { cesky: "vlak", en: "train", de: "zug", es: "tren", nl: "trein", fr: "train", sv: "tåg", ru: "поезд", it: "treno" },
        { cesky: "kolo", en: "bicycle", de: "fahrrad", es: "bicicleta", nl: "fiets", fr: "vélo", sv: "cykel", ru: "велосипед", it: "bicicletta" },
        { cesky: "letadlo", en: "plane", de: "flugzeug", es: "avión", nl: "vliegtuig", fr: "avion", sv: "flygplan", ru: "самолет", it: "aereo" },
        { cesky: "motorka", en: "motorbike", de: "motorrad", es: "moto", nl: "motorfiets", fr: "moto", sv: "motorcykel", ru: "мотоцикл", it: "moto" }
    ],
    jidlo: [
        { cesky: "jablko", en: "apple", de: "apfel", es: "manzana", nl: "appel", fr: "pomme", sv: "äpple", ru: "яблоко", it: "mela" },
        { cesky: "banán", en: "banana", de: "banane", es: "plátano", nl: "banaan", fr: "banane", sv: "banan", ru: "банан", it: "banana" },
        { cesky: "pomeranč", en: "orange", de: "orange", es: "naranja", nl: "sinaasappel", fr: "orange", sv: "apelsin", ru: "апельсин", it: "arancia" },
        { cesky: "jahoda", en: "strawberry", de: "erdbeere", es: "fresa", nl: "aardbei", fr: "fraise", sv: "jordgubbe", ru: "клубника", it: "fragola" },
        { cesky: "citrón", en: "lemon", de: "zitrone", es: "limón", nl: "citroen", fr: "citron", sv: "citron", ru: "лимон", it: "limone" },
        { cesky: "hroznové víno", en: "grapes", de: "trauben", es: "uvas", nl: "druiven", fr: "raisins", sv: "druvor", ru: "виноград", it: "uva" },
        { cesky: "broskev", en: "peach", de: "pfirsich", es: "melocotón", nl: "perzik", fr: "pêche", sv: "persika", ru: "персик", it: "pesca" },
        { cesky: "hruška", en: "pear", de: "birne", es: "pera", nl: "peer", fr: "poire", sv: "päron", ru: "груша", it: "pera" },
        { cesky: "rajče", en: "tomato", de: "tomate", es: "tomate", nl: "tomaat", fr: "tomate", sv: "tomat", ru: "помидор", it: "pomodoro" },
        { cesky: "brambor", en: "potato", de: "kartoffel", es: "patata", nl: "aardappel", fr: "pomme de terre", sv: "potatis", ru: "картошка", it: "patata" },
        { cesky: "mrkev", en: "carrot", de: "karotte", es: "zanahoria", nl: "wortel", fr: "carotte", sv: "morot", ru: "морковь", it: "carota" },
        { cesky: "cibule", en: "onion", de: "zwiebel", es: "cebolla", nl: "ui", fr: "oignon", sv: "lök", ru: "лук", it: "cipolla" },
        { cesky: "česnek", en: "garlic", de: "knoblauch", es: "ajo", nl: "knoflook", fr: "ail", sv: "vitlök", ru: "чеснок", it: "aglio" },
        { cesky: "paprika", en: "pepper", de: "paprika", es: "pimiento", nl: "paprika", fr: "poivron", sv: "paprika", ru: "перец", it: "peperone" },
        { cesky: "mleko", en: "milk", de: "milch", es: "leche", nl: "melk", fr: "lait", sv: "mjölk", ru: "молоко", it: "latte" },
        { cesky: "maso", en: "meat", de: "fleisch", es: "carne", nl: "vlees", fr: "viande", sv: "kött", ru: "мясо", it: "carne" },
        { cesky: "rýže", en: "rice", de: "reis", es: "arroz", nl: "rijst", fr: "riz", sv: "ris", ru: "рис", it: "riso" },
        { cesky: "chléb", en: "bread", de: "brot", es: "pan", nl: "brood", fr: "pain", sv: "bröd", ru: "хлеб", it: "pane" },
        { cesky: "salát", en: "salad", de: "salat", es: "ensalada", nl: "salade", fr: "salade", sv: "sallad", ru: "салат", it: "insalata" }
    ],
    osobni_udaje: [
        { cesky: "jméno", en: "name", de: "name", es: "nombre", nl: "naam", fr: "nom", sv: "namn", ru: "имя", it: "nome" },
        { cesky: "příjmení", en: "surname", de: "nachname", es: "apellido", nl: "achternaam", fr: "nom de famille", sv: "efternamn", ru: "фамилия", it: "cognome" },
        { cesky: "věk", en: "age", de: "alter", es: "edad", nl: "leeftijd", fr: "âge", sv: "ålder", ru: "возраст", it: "età" },
        { cesky: "jméno", en: "first name", de: "vorname", es: "nombre de pila", nl: "voornaam", fr: "prénom", sv: "förnamn", ru: "имя", it: "nome di battesimo" },
        { cesky: "adresa", en: "address", de: "adresse", es: "dirección", nl: "adres", fr: "adresse", sv: "adress", ru: "адрес", it: "indirizzo" }
    ],
    slovesa: [
        { cesky: "být", en: "be", de: "sein", es: "ser" },
  { cesky: "mít", en: "have", de: "haben", es: "tener" },
  { cesky: "stát se", en: "become", de: "werden", es: "llegar a ser" },

  // ZPŮSOBOVÁ SLOVESA
  { cesky: "moci / umět", en: "can / be able to", de: "können", es: "poder" },
  { cesky: "muset", en: "must / have to", de: "müssen", es: "tener que" },
  { cesky: "smět", en: "be allowed to", de: "dürfen", es: "poder (permiso)" },
  { cesky: "chtít", en: "want", de: "wollen", es: "querer" },
  { cesky: "mít povinnost / dělati (měl by)", en: "should / ought to", de: "sollen", es: "deber" },
  { cesky: "mít rád", en: "like", de: "mögen", es: "gustar" },
  { cesky: "chtěl by", en: "would like", de: "möchten", es: "gustaría" },

  // BĚŽNÁ SLOVESA DENNÍ POTŘEBY (A–G)
  { cesky: "dělat", en: "do / make", de: "machen", es: "hacer" },
  { cesky: "jít / kráčet", en: "go / walk", de: "gehen", es: "ir" },
  { cesky: "přijít", en: "come", de: "kommen", es: "venir" },
  { cesky: "jet / cestovat", en: "drive / ride", de: "fahren", es: "conducir / ir en vehículo" },
  { cesky: "vidět", en: "see", de: "sehen", es: "ver" },
  { cesky: "číst", en: "read", de: "lesen", es: "leer" },
  { cesky: "psát", en: "write", de: "schreiben", es: "escribir" },
  { cesky: "mluvit", en: "speak / talk", de: "sprechen", es: "hablar" },
  { cesky: "jíst", en: "eat", de: "essen", es: "comer" },
  { cesky: "pít", en: "drink", de: "trinken", es: "beber" },
  { cesky: "spát", en: "sleep", de: "schlafen", es: "dormir" },
  { cesky: "pracovat", en: "work", de: "arbeiten", es: "trabajar" },
  { cesky: "bydlet", en: "live / reside", de: "wohnen", es: "vivir / residir" },
  { cesky: "koupit", en: "buy", de: "kaufen", es: "comprar" },
  { cesky: "dát / dát něco někomu", en: "give", de: "geben", es: "dar" },
  { cesky: "vzít", en: "take", de: "nehmen", es: "tomar / coger" },
  { cesky: "pomoci", en: "help", de: "helfen", es: "ayudar" },
  { cesky: "najít", en: "find", de: "finden", es: "encontrar" },
  { cesky: "myslet", en: "think", de: "denken", es: "pensar" },
  { cesky: "vědět", en: "know (facts)", de: "wissen", es: "saber" },
  { cesky: "znát", en: "know (person/place)", de: "kennen", es: "conocer" },
  { cesky: "říkat / sdělit", en: "say / tell", de: "sagen", es: "decir" },
  { cesky: "ptát se", en: "ask", de: "fragen", es: "preguntar" },
  { cesky: "odpovědět", en: "answer", de: "antworten", es: "responder" },
  { cesky: "děkovat", en: "thank", de: "danken", es: "agradecer" },
  { cesky: "běžet", en: "run", de: "laufen", es: "correr" },
  { cesky: "létat", en: "fly", de: "fliegen", es: "volar" },
  { cesky: "zůstat", en: "stay / remain", de: "bleiben", es: "quedarse / permanecer" },
  { cesky: "potkat / setkat se", en: "meet", de: "treffen", es: "encontrar / quedar" },
  { cesky: "přinést", en: "bring", de: "bringen", es: "traer" },
  { cesky: "nosit / mít na sobě", en: "wear / carry", de: "tragen", es: "llevar / vestir" },
  { cesky: "zapomenout", en: "forget", de: "vergessen", es: "olvidar" },
  { cesky: "ztratit", en: "lose", de: "verlieren", es: "perder" },
  { cesky: "platit", en: "pay", de: "bezahlen", es: "pagar" },
  { cesky: "platit / stát (o ceně)", en: "cost", de: "kosten", es: "costar" },
  { cesky: "učit se", en: "learn / study", de: "lernen", es: "aprender" },
  { cesky: "studovat (na VŠ)", en: "study", de: "studieren", es: "estudiar" },
  { cesky: "hrát", en: "play", de: "spielen", es: "jugar / tocar" },
  { cesky: "slyšet", en: "hear", de: "hören", es: "oír / escuchar" },
  { cesky: "poslouchat", en: "listen", de: "zuhören", es: "escuchar" },
  { cesky: "vařit", en: "cook", de: "kochen", es: "cocinar" },
  { cesky: "pečení / péct", en: "bake", de: "backen", es: "hornear" },
  { cesky: "žít", en: "live", de: "leben", es: "vivir" },
  { cesky: "mít rád / milovat", en: "love", de: "lieben", es: "amar" },
  { cesky: "smát se", en: "laugh", de: "lachen", es: "reír" },
  { cesky: "plakat", en: "cry", de: "weinen", es: "llorar" },

  // BĚŽNÁ SLOVESA DENNÍ POTŘEBY (H–Z)
  { cesky: "čekat", en: "wait", de: "warten", es: "esperar" },
  { cesky: "hledat", en: "search / look for", de: "suchen", es: "buscar" },
  { cesky: "potřebovat", en: "need", de: "brauchen", es: "necesitar" },
  { cesky: "věřit", en: "believe", de: "glauben", es: "creer" },
  { cesky: "doufat", en: "hope", de: "hoffen", es: "esperar (tener esperanza)" },
  { cesky: "přát si", en: "wish", de: "wünschen", es: "desear" },
  { cesky: "ukázat", en: "show", de: "zeigen", es: "mostrar / enseñar" },
  { cesky: "vysvětlit", en: "explain", de: "erklären", es: "explicar" },
  { cesky: "rozumět", en: "understand", de: "verstehen", es: "entender" },
  { cesky: "znamenat", en: "mean", de: "bedeuten", es: "significar" },
  { cesky: "otevřít", en: "open", de: "öffnen", es: "abrir" },
  { cesky: "zavřít", en: "close", de: "schließen", es: "cerrar" },
  { cesky: "začít", en: "begin", de: "beginnen", es: "empezar" },
  { cesky: "končit", en: "end / finish", de: "enden", es: "terminar" },
  { cesky: "přestat", en: "stop", de: "aufhören", es: "parar / dejar de" },
  { cesky: "sedět", en: "sit", de: "sitzen", es: "estar sentado" },
  { cesky: "posadit se", en: "sit down", de: "sich setzen", es: "sentarse" },
  { cesky: "stát", en: "stand", de: "stehen", es: "estar de pie" },
  { cesky: "postavit", en: "put / set up", de: "stellen", es: "poner de pie" },
  { cesky: "ležet", en: "lie", de: "liegen", es: "estar tumbado" },
  { cesky: "položit", en: "lay / put down", de: "legen", es: "poner en horizontal" },
  { cesky: "viset", en: "hang", de: "hängen", es: "colgar / estar colgado" },
  { cesky: "pověsit", en: "hang up", de: "aufhängen", es: "colgar" },
  { cesky: "sahat / dát", en: "put / place", de: "stecken", es: "meter / poner" },
  { cesky: "padat / padnout", en: "fall", de: "fallen", es: "caer" },
  { cesky: "skákat", en: "jump", de: "springen", es: "saltar" },
  { cesky: "plavat", en: "swim", de: "schwimmen", es: "nadar" },
  { cesky: "tančit", en: "dance", de: "tanzen", es: "bailar" },
  { cesky: "zpívat", en: "sing", de: "singen", es: "cantar" },
  { cesky: "malovat / kreslit", en: "paint / draw", de: "malen", es: "pintar / dibujar" },
  { cesky: "kreslit", en: "draw", de: "zeichnen", es: "dibujar" },
  { cesky: "fotografovat", en: "photograph", de: "fotografieren", es: "fotografiar" },
  { cesky: "cestovat", en: "travel", de: "reisen", es: "viajar" },
  { cesky: "balit", en: "pack", de: "packen", es: "empacar" },
  { cesky: "mýt / prát", en: "wash", de: "waschen", es: "lavar" },
  { cesky: "čistit", en: "clean", de: "putzen", es: "limpiar" },
  { cesky: "uklízet", en: "clean up", de: "aufräumen", es: "ordenar" },
  { cesky: "sprchovat se", en: "shower", de: "duschen", es: "ducharse" },
  { cesky: "koupat se", en: "bathe", de: "baden", es: "bañarse" },
  { cesky: "holit se", en: "shave", de: "rasieren", es: "afeitarse" },
  { cesky: "česat se", en: "comb", de: "kämmen", es: "peinarse" },
  { cesky: "oblékat se", en: "dress / put on", de: "anziehen", es: "vestirse" },
  { cesky: "svlékat se", en: "undress", de: "ausziehen", es: "desvestirse" },
  { cesky: "převlékat se", en: "change clothes", de: "umziehen", es: "cambiarse de ropa" },

  // SLOVESA S PŘEDPONAMI (ODLUČITELNÁ A NEODLUČITELNÁ)
  { cesky: "nakupovat", en: "shop", de: "einkaufen", es: "comprar" },
  { cesky: "vstávat", en: "get up", de: "aufstehen", es: "levantarse" },
  { cesky: "zavolat (telefonem)", en: "call", de: "anrufen", es: "llamar" },
  { cesky: "přijít / dorazit", en: "arrive", de: "ankommen", es: "llegar" },
  { cesky: "odjet", en: "depart", de: "abfahren", es: "salir (vehículo)" },
  { cesky: "odletět", en: "depart (plane)", de: "abfliegen", es: "despegar" },
  { cesky: "jít s někým / jít spolu", en: "come along", de: "mitkommen", es: "acompañar" },
  { cesky: "vznášet se / vzít s sebou", en: "take along", de: "mitnehmen", es: "llevar consigo" },
  { cesky: "přinést s sebou", en: "bring along", de: "mitbringen", es: "traer consigo" },
  { cesky: "díval se na TV", en: "watch TV", de: "fernsehen", es: "ver la televisión" },
  { cesky: "vypadat", en: "look like / appear", de: "aussehen", es: "parecer" },
  { cesky: "představit se / představit si", en: "introduce / imagine", de: "vorstellen", es: "presentar / imaginar" },
  { cesky: "připravit", en: "prepare", de: "vorbereiten", es: "preparar" },
  { cesky: "začít (opět)", en: "start", de: "anfangen", es: "empezar" },
  { cesky: "nabídnout", en: "offer", de: "anbieten", es: "ofrecer" },
  { cesky: "přijmout", en: "accept", de: "annehmen", es: "aceptar" },
  { cesky: "přestoupit (doprava)", en: "change trains", de: "umsteigen", es: "cambiar de tren/autobús" },
  { cesky: "nastoupit", en: "get in", de: "einsteigen", es: "subir a un vehículo" },
  { cesky: "vystoupit", en: "get out", de: "aussteigen", es: "bajar de un vehículo" },
  { cesky: "pozvat", en: "invite", de: "einladen", es: "invitar" },
  { cesky: "doporučit", en: "recommend", de: "empfehlen", es: "recomendar" },
  { cesky: "obdržet / dostat", en: "receive / get", de: "bekommen", es: "recibir / obtener" },
  { cesky: "zapomenout", en: "forget", de: "vergessen", es: "olvidar" },
  { cesky: "prohrát / ztratit", en: "lose", de: "verlieren", es: "perder" },
  { cesky: "pronajmout", en: "rent", de: "vermieten", es: "alquilar (dar en alquiler)" },
  { cesky: "najmout si", en: "rent", de: "mieten", es: "alquilar (tomar en alquiler)" },
  { cesky: "prodat", en: "sell", de: "verkaufen", es: "vender" },
  { cesky: "platit", en: "pay", de: "bezahlen", es: "pagar" },
  { cesky: "platit / vyplatit", en: "pay", de: "zahlen", es: "pagar" },
  { cesky: "popsat", en: "describe", de: "beschreiben", es: "describir" },
  { cesky: "navštívit", en: "visit", de: "besuchen", es: "visitar" },
  { cesky: "prohlédnout si", en: "visit / view", de: "besichtigen", es: "visitar / contemplar" },
  { cesky: "objednat", en: "order", de: "bestellen", es: "pedir / encargar" },

  // NEPRAVIDELNÁ / SILNÁ SLOVESA (ROZŠÍŘENÍ)
  { cesky: "nechat / dovolit", en: "let / allow", de: "lassen", es: "dejar / permitir" },
  { cesky: "držet", en: "hold", de: "halten", es: "sostener / parar" },
  { cesky: "srovnat / porovnat", en: "compare", de: "vergleichen", es: "comparar" },
  { cesky: "vyhrát", en: "win", de: "gewinnen", es: "ganar" },
  { cesky: "spadnout", en: "fall", de: "fallen", es: "caer" },
  { cesky: "rozhodnout", en: "decide", de: "entscheiden", es: "decidir" },
  { cesky: "stříhat / řezat", en: "cut", de: "schneiden", es: "cortar" },
  { cesky: "spát", en: "sleep", de: "schlafen", es: "dormir" },
  { cesky: "ublížit / bolet", en: "hurt", de: "weh tun", es: "doler" },
  { cesky: "bít / udeřit", en: "hit / beat", de: "schlagen", es: "golpear" },
  { cesky: "nést / nosit", en: "carry / wear", de: "tragen", es: "llevar" },
  { cesky: "stát (o ceně)", en: "cost", de: "kosten", es: "costar" },
  { cesky: "stáhnout / táhnout", en: "pull / move", de: "ziehen", es: "tirar / mudarse" },
  { cesky: "stěhovat se", en: "move (house)", de: "umziehen", es: "mudarse" },
  { cesky: "tlačit / strčit", en: "push", de: "schieben", es: "empujar" },
  { cesky: "házet", en: "throw", de: "werfen", es: "tirar / lanzar" },
  { cesky: "půjčit", en: "lend", de: "leihen", es: "prestar" },

  // ZVRATNÁ A VAZEBNÁ SLOVESA
  { cesky: "těšit se (na)", en: "look forward to", de: "sich freuen auf", es: "alegrarse de" },
  { cesky: "mít radost (z)", en: "be glad about", de: "sich freuen über", es: "alegrarse por" },
  { cesky: "zajímat se (o)", en: "be interested in", de: "sich interessieren für", es: "interesarse por" },
  { cesky: "zlobit se (na)", en: "be angry with", de: "sich ärgern über", es: "enfadarse con" },
  { cesky: "cítit se", en: "feel", de: "sich fühlen", es: "sentirse" },
  { cesky: "omluvit se", en: "apologize", de: "sich entschuldigen", es: "disculparse" },
  { cesky: "stěžovat si", en: "complain", de: "sich beschweren", es: "quejarse" },
  { cesky: "všimnout si", en: "notice", de: "bemerken", es: "darse cuenta de" },
  { cesky: "starat se (o)", en: "take care of", de: "sich kümmern um", es: "cuidar de" },
  { cesky: "pamatovat si / vzpomenout si", en: "remember", de: "sich erinnern an", es: "acordarse de" },
  { cesky: "soustředit se", en: "concentrate", de: "sich konzentrieren", es: "concentrarse" },
  { cesky: "odpočinout si", en: "relax / rest", de: "sich ausruhen", es: "descansar" },
  { cesky: "přihlásit se", en: "register / log in", de: "sich anmelden", es: "registrarse" },
  { cesky: "odhlásit se", en: "log out", de: "sich abmelden", es: "cerrar sesión" },

  // SLUŽBY, NÁKUPY A PRÁCE
  { cesky: "platit v hotovosti", en: "pay cash", de: "bar bezahlen", es: "pagar en efectivo" },
  { cesky: "vyměnit", en: "exchange", de: "tauschen", es: "cambiar" },
  { cesky: "zarezervovat", en: "book / reserve", de: "buchen / reservieren", es: "reservar" },
  { cesky: "zrušit / odvolat", en: "cancel", de: "absagen", es: "cancelar" },
  { cesky: "potvrdit", en: "confirm", de: "bestätigen", es: "confirmar" },
  { cesky: "podepsat", en: "sign", de: "unterschreiben", es: "firmar" },
  { cesky: "vyplnit (formulář)", en: "fill in", de: "ausfüllen", es: "rellenar" },
  { cesky: "poslat", en: "send", de: "schicken / senden", es: "enviar" },
  { cesky: "obdržet", en: "receive", de: "erhalten", es: "recibir" },
  { cesky: "předat", en: "hand over", de: "übergeben", es: "entregar" },
  { cesky: "vydělávat (peníze)", en: "earn (money)", de: "verdienen", es: "ganar (dinero)" },
  { cesky: "utrácet (peníze)", en: "spend (money)", de: "ausgeben", es: "gastar" },
  { cesky: "šetřit", en: "save (money)", de: "sparen", es: "ahorrar" },
  { cesky: "darovat", en: "donate / give as gift", de: "schenken", es: "regalar" },

  // CESTOVÁNÍ, ZDRAVÍ A VOLNÝ ČAS
  { cesky: "letět", en: "fly", de: "fliegen", es: "volar" },
  { cesky: "řídit (auto)", en: "drive", de: "steuern / fahren", es: "conducir" },
  { cesky: "parkovat", en: "park", de: "parken", es: "aparcar" },
  { cesky: "tankovat", en: "refuel", de: "tanken", es: "repostar" },
  { cesky: "zabloudit", en: "get lost", de: "sich verlaufen", es: "extraviarse" },
  { cesky: "navštívit (lékaře)", en: "consult / visit", de: "aufsuchen", es: "consultar" },
  { cesky: "vyšetřit", en: "examine", de: "untersuchen", es: "examinar" },
  { cesky: "předepsat (lék)", en: "prescribe", de: "verschreiben", es: "recetar" },
  { cesky: "chybět", en: "miss / be absent", de: "fehlen", es: "faltar" },
  { cesky: "bolet", en: "ache / hurt", de: "schmerzen", es: "doler" },
  { cesky: "uzdravit se", en: "recover", de: "gesund werden", es: "curarse" },
  { cesky: "slavit", en: "celebrate", de: "feiern", es: "celebrar" },
  { cesky: "bavit se / užívat si", en: "have fun", de: "Spaß haben", es: "divertirse" },
  { cesky: "organizovat", en: "organize", de: "organisieren", es: "organizar" },
  { cesky: "plánovat", en: "plan", de: "planen", es: "planificar" },
  { cesky: "povídat si", en: "chat / talk", de: "sprechen / sich unterhalten", es: "charlar" },
  { cesky: "diskutovat", en: "discuss", de: "diskutieren", es: "discutir" },
  { cesky: "souhlasit", en: "agree", de: "zustimmen", es: "estar de acuerdo" },
  { cesky: "nesouhlasit", en: "disagree", de: "widersprechen", es: "no estar de acuerdo" },
  { cesky: "sjet / myslet si", en: "think / opinion", de: "meinen", es: "opinar" },
  { cesky: "doporučit", en: "suggest", de: "vorschlagen", es: "proponer" },
  { cesky: "rádit / poradit", en: "advise", de: "raten", es: "aconsejar" },
  { cesky: "varovat", en: "warn", de: "warnen", es: "advertir" },
  { cesky: "slíbit", en: "promise", de: "versprechen", es: "prometer" },
  { cesky: "lhát", en: "lie", de: "lügen", es: "mentir" },
  { cesky: "mlčet", en: "be silent", de: "schweigen", es: "callar" },
  { cesky: "pršet", en: "rain", de: "regnen", es: "llover" },
  { cesky: "sněžit", en: "snow", de: "schneien", es: "nevar" },
  { cesky: "foukat (vítr)", en: "blow", de: "wehen / blasen", es: "soplar" },
  { cesky: "svítit (slunce)", en: "shine", de: "scheinen", es: "brillar" },
  { cesky: "stmívat se", en: "get dark", de: "dunkel werden", es: "anochecer" },
  { cesky: "mrazit", en: "freeze", de: "frieren", es: "helar" },
  { cesky: "horořet / pálit", en: "burn", de: "brennen", es: "arder" },


  { cesky: "vařit (voda)", en: "boil", de: "kochen", es: "hervir" },
  { cesky: "smažit", en: "fry", de: "braten", es: "freír" },
  { cesky: "krájet", en: "slice / cut", de: "schneiden", es: "cortar" },
  { cesky: "míchat", en: "mix / stir", de: "mischen / rühren", es: "mezclar" },
  { cesky: "prostřít (stůl)", en: "set (the table)", de: "den Tisch decken", es: "poner la mesa" },
  { cesky: "sklidit (ze stolu)", en: "clear (the table)", de: "den Tisch abräumen", es: "recoger la mesa" },
  { cesky: "mýt nádobí", en: "wash dishes", de: "spülen / geschirr spülen", es: "fregar los platos" },
  { cesky: "vysávat", en: "vacuum", de: "staubsaugen", es: "pasar la aspiradora" },
  { cesky: "žehlit", en: "iron", de: "bügeln", es: "planchar" },
  { cesky: "opravit", en: "repair", de: "reparieren", es: "reparar" },
  { cesky: "fungovat", en: "work / function", de: "funktionieren", es: "funcionar" },
  { cesky: "rozbít se", en: "break", de: "kaputtgehen", es: "romperse" },

  // DALŠÍ DŮLEŽITÁ SLOVESA A2
  { cesky: "patřit", en: "belong", de: "gehören", es: "pertenecer" },
  { cesky: "chutnat", en: "taste", de: "schmecken", es: "gustar (comida)" },
  { cesky: "slušet (oblečení)", en: "suit / fit", de: "stehen / passen", es: "sentar bien" },
  { cesky: "předcházet / dít se", en: "happen", de: "passieren", es: "pasar / ocurrir" },
  { cesky: "stát se (událost)", en: "happen / take place", de: "stattfinden", es: "tener lugar" },
  { cesky: "pokračovat", en: "continue", de: "weitermachen / fortfahren", es: "continuar" },
  { cesky: "změnit", en: "change", de: "ändern", es: "cambiar" },
  { cesky: "zlepšit", en: "improve", de: "verbessern", es: "mejorar" },
  { cesky: "zhoršit", en: "worsen", de: "verschlechtern", es: "empeorar" },
  { cesky: "vyhrát", en: "win", de: "gewinnen", es: "ganar" },
  { cesky: "prohrát", en: "lose", de: "verlieren", es: "perder" },
  { cesky: "používat", en: "use", de: "benutzen / verwenden", es: "usar" },
  { cesky: "zkusit / ochutnat", en: "try / taste", de: "probieren / versuchen", es: "probar / intentar" },
  { cesky: "stihnout / dokázat", en: "manage / make it", de: "schaffen", es: "conseguir / lograr" },
  { cesky: "vypnout (přístroj)", en: "turn off", de: "ausschalten", es: "apagar" },
  { cesky: "zapnout (přístroj)", en: "turn on", de: "einschalten", es: "encender" },
  { cesky: "stáhnout (z internetu)", en: "download", de: "herunterladen", es: "descargar" },
  { cesky: "poslat e-mail", en: "email", de: "mailen", es: "enviar un correo" },
  { cesky: "kliknout", en: "click", de: "klicken", es: "hacer clic" },
  { cesky: "tvořit / stavět", en: "build / create", de: "bauen", es: "construir" },
  { cesky: "malovat", en: "paint", de: "malen", es: "pintar" },
  { cesky: "vytvořit", en: "create", de: "erstellen", es: "crear" },
  { cesky: "trvat (časově)", en: "take time / last", de: "dauern", es: "durar" },
  { cesky: "zůstat stát / zastavit", en: "stop", de: "anhalten", es: "detenerse" },
  { cesky: "přejít / překročit", en: "cross", de: "überqueren", es: "cruzar" },
  { cesky: "zatáhnout / odbočit", en: "turn", de: "abbiegen", es: "girar" },
  { cesky: "pokračovat rovně", en: "go straight", de: "geradeaus gehen", es: "ir recto" },
  { cesky: "potkat", en: "meet / encounter", de: "begegnen", es: "encontrar" },
  { cesky: "pozdravit", en: "greet", de: "grüßen", es: "saludar" },
  { cesky: "rozloučit se", en: "say goodbye", de: "sich verabschieden", es: "despedirse" },
  { cesky: "blahopřát", en: "congratulate", de: "gratulieren", es: "felicitar" },
  { cesky: "překvapit", en: "surprise", de: "überraschen", es: "sorprender" },
  { cesky: "vylekat se", en: "be frightened", de: "erschrecken", es: "asustarse" },
  { cesky: "doufat", en: "hope", de: "hoffen", es: "esperar" },
  { cesky: "zůstat zdravý", en: "stay healthy", de: "gesund bleiben", es: "mantenerse sano" },
  { cesky: "přibrat (na váze)", en: "gain weight", de: "zunehmen", es: "ganar peso" },
  { cesky: "hubnout", en: "lose weight", de: "abnehmen", es: "perder peso" },
  { cesky: "kouřit", en: "smoke", de: "rauchen", es: "fumar" },
  { cesky: "vzdát se / přestat s", en: "give up", de: "aufgeben", es: "rendirse / dejar" },
  { cesky: "stýskat se", en: "miss", de: "vermissen", es: "echar de menos" },
  { cesky: "pamatovat", en: "remember", de: "behalten", es: "recordar" },
  { cesky: "doprovodit", en: "accompany", de: "begleiten", es: "acompañar" },
  { cesky: "zazvonit", en: "ring", de: "klingeln", es: "sonar / llamar al timbre" },
  { cesky: "ztratit se", en: "get lost", de: "verloren gehen", es: "perderse" },
  { cesky: "najít cestu", en: "find the way", de: "den Weg finden", es: "encontrar el camino" }

   
]
};