const centralniDatabaze = {
    barvy: [
        { cesky: "červená", en: "red", de: "rot", es: "rojo", nl: "rood", fr: "rouge", sv: "röd", ru: "красный", it: "rosso" },
        { cesky: "modrá", en: "blue", de: "blau", es: "azul", nl: "blauw", fr: "bleu", sv: "blå", ru: "синий", it: "blu" },
        { cesky: "zelená", en: "green", de: "grün", es: "verde", nl: "groen", fr: "vert", sv: "grön", ru: "зеленый", it: "verde" },
        { cesky: "žlutá", en: "yellow", de: "gelb", es: "amarillo", nl: "geel", fr: "jaune", sv: "gul", ru: "желтый", it: "giallo" },
        { cesky: "černá", en: "black", de: "schwarz", es: "negro", nl: "zwart", fr: "noir", sv: "svart", ru: "черный", it: "nero" },
        { cesky: "bílá", en: "white", de: "weiß", es: "blanco", nl: "wit", fr: "blanc", sv: "vit", ru: "белый", it: "bianco" },
        { cesky: "oranžová", en: "orange", de: "orange", es: "naranja", nl: "oranje", fr: "orange", sv: "orange", ru: "оранжевый", it: "arancione" },
        { cesky: "růžová", en: "pink", de: "rosa", es: "rosa", nl: "roze", fr: "rose", sv: "rosa", ru: "розовый", it: "rosa" },
        { cesky: "šedá", en: "grey", de: "grau", es: "gris", nl: "grijs", fr: "gris", sv: "grå", ru: "серый", it: "grigio" }
    ],
    cisla: [
        { cesky: "jedna", en: "one", de: "eins", es: "uno", nl: "één", fr: "un", sv: "ett", ru: "один", it: "uno" },
        { cesky: "dva", en: "two", de: "zwei", es: "dos", nl: "twee", fr: "deux", sv: "två", ru: "два", it: "due" },
        { cesky: "tři", en: "three", de: "drei", es: "tres", nl: "drie", fr: "trois", sv: "tre", ru: "три", it: "tre" },
        { cesky: "čtyři", en: "four", de: "vier", es: "cuatro", nl: "vier", fr: "quatre", sv: "fyra", ru: "четыре", it: "quattro" },
        { cesky: "pět", en: "five", de: "fünf", es: "cinco", nl: "vijf", fr: "cinq", sv: "fem", ru: "пять", it: "cinque" },
        { cesky: "šest", en: "six", de: "sechs", es: "seis", nl: "zes", fr: "six", sv: "sex", ru: "шесть", it: "sei" },
        { cesky: "sedm", en: "seven", de: "sieben", es: "siete", nl: "zeven", fr: "sept", sv: "sju", ru: "семь", it: "sette" },
        { cesky: "osm", en: "eight", de: "acht", es: "ocho", nl: "acht", fr: "huit", sv: "åtta", ru: "восемь", it: "otto" },
        { cesky: "devět", en: "nine", de: "neun", es: "nueve", nl: "negen", fr: "neuf", sv: "nio", ru: "девать", it: "nove" },
        { cesky: "deset", en: "ten", de: "zehn", es: "diez", nl: "tien", fr: "dix", sv: "tio", ru: "десять", it: "dieci" },
        { cesky: "jedenáct", en: "eleven", de: "elf", es: "once", nl: "elf", fr: "onze", sv: "elva", ru: "одиннадцать", it: "undici" },
        { cesky: "dvanáct", en: "twelve", de: "zwölf", es: "doce", nl: "twaalf", fr: "douze", sv: "tolv", ru: "двенадцать", it: "dodici" },
        { cesky: "třináct", en: "thirteen", de: "dreizehn", es: "trece", nl: "dertien", fr: "treize", sv: "tretton", ru: "тринадцать", it: "tredici" },
        { cesky: "čtrnáct", en: "fourteen", de: "vierzehn", es: "catorce", nl: "veertien", fr: "quatorze", sv: "fjorton", ru: "четырнадцать", it: "quattordici" },
        { cesky: "patnáct", en: "fifteen", de: "fünfzehn", es: "quince", nl: "vijftien", fr: "quinze", sv: "femton", ru: "пятнадцать", it: "quindici" },
        { cesky: "šestnáct", en: "sixteen", de: "sechzehn", es: "diecisiete", nl: "zestien", fr: "seize", sv: "sexton", ru: "шестнадцать", it: "sedici" },
        { cesky: "sedmnáct", en: "seventeen", de: "siebzehn", es: "diecisiete", nl: "zeventien", fr: "dix-sept", sv: "sjutton", ru: "семнадцать", it: "diciassette" },
        { cesky: "osmnáct", en: "eighteen", de: "achtzehn", es: "dieciocho", nl: "achtien", fr: "dix-huit", sv: "arton", ru: "восемнадцать", it: "diciotto" },
        { cesky: "devatenáct", en: "nineteen", de: "neunzehn", es: "diecinueve", nl: "negentien", fr: "dix-neuf", sv: "nitton", ru: "девятнадцать", it: "diciannove" },
        { cesky: "dvacet", en: "twenty", de: "zwanzig", es: "veinte", nl: "twintig", fr: "vingt", sv: "tjugo", ru: "двадцать", it: "venti" },
        { cesky: "sto", en: "hundred", de: "hundert", es: "cien", nl: "honderd", fr: "cent", sv: "hundra", ru: "сто", it: "cento" },
        { cesky: "tisíc", en: "thousand", de: "tausend", es: "mil", nl: "duizend", fr: "mille", sv: "tusen", ru: "тысяча", it: "mille" }
    ],
    dny_v_tydnu: [
        { cesky: "pondělí", en: "monday", de: "montag", es: "lunes", nl: "maandag", fr: "lundi", sv: "måndag", ru: "понедельник", it: "lunedì" },
        { cesky: "úterý", en: "tuesday", de: "dienstag", es: "martes", nl: "dinsdag", fr: "mardi", sv: "tisdag", ru: "вторник", it: "martedì" },
        { cesky: "středa", en: "wednesday", de: "mittwoch", es: "miércoles", nl: "woensdag", fr: "mercredi", sv: "onsdag", ru: "среда", it: "mercoledì" },
        { cesky: "čtvrtek", en: "thursday", de: "donnerstag", es: "jueves", nl: "donderdag", fr: "jeudi", sv: "torsdag", ru: "четверг", it: "giovedì" },
        { cesky: "pátek", en: "friday", de: "freitag", es: "viernes", nl: "vrijdag", fr: "vendredi", sv: "fredag", ru: "пятница", it: "venerdì" },
        { cesky: "sobota", en: "saturday", de: "samstag", es: "sábado", nl: "zaterdag", fr: "samedi", sv: "lördag", ru: "суббота", it: "sabato" },
        { cesky: "neděle", en: "sunday", de: "sonntag", es: "domingo", nl: "zondag", fr: "dimanche", sv: "söndag", ru: "воскресенье", it: "domenica" }
    ],
    mesice: [
        { cesky: "leden", en: "january", de: "januar", es: "enero", nl: "januari", fr: "janvier", sv: "januari", ru: "январь", it: "gennaio" },
        { cesky: "únor", en: "february", de: "februar", es: "febrero", nl: "februari", fr: "février", sv: "februari", ru: "февраль", it: "febbraio" },
        { cesky: "březen", en: "march", de: "märz", es: "marzo", nl: "maart", fr: "mars", sv: "mars", ru: "март", it: "marzo" },
        { cesky: "duben", en: "april", de: "april", es: "abril", nl: "april", fr: "avril", sv: "april", ru: "апрель", it: "aprile" },
        { cesky: "květen", en: "may", de: "mai", es: "mayo", nl: "mei", fr: "mai", sv: "maj", ru: "май", it: "maggio" },
        { cesky: "červen", en: "june", de: "juni", es: "junio", nl: "juni", fr: "juin", sv: "juni", ru: "июнь", it: "giugno" },
        { cesky: "červenec", en: "july", de: "juli", es: "julio", nl: "juli", fr: "juillet", sv: "juli", ru: "июль", it: "luglio" },
        { cesky: "srpen", en: "august", de: "august", es: "agosto", nl: "augustus", fr: "août", sv: "augusti", ru: "август", it: "agosto" },
        { cesky: "září", en: "september", de: "september", es: "septiembre", nl: "september", fr: "septembre", sv: "september", ru: "сентябрь", it: "settembre" },
        { cesky: "říjen", en: "october", de: "oktober", es: "octubre", nl: "oktober", fr: "octobre", sv: "oktober", ru: "октябрь", it: "ottobre" },
        { cesky: "listopad", en: "november", de: "november", es: "noviembre", nl: "november", fr: "novembre", sv: "november", ru: "ноябрь", it: "novembre" },
        { cesky: "prosinec", en: "december", de: "dezember", es: "diciembre", nl: "december", fr: "décembre", sv: "december", ru: "декабрь", it: "dicembre" }
    ],
    zakladni_fraze: [
        { cesky: "ahoj", en: "hello", de: "hallo", es: "hola", nl: "hallo", fr: "salut", sv: "hej", ru: "привет", it: "ciao" },
        { cesky: "dobré ráno", en: "good morning", de: "guten morgen", es: "buenos días", nl: "goedemorgen", fr: "bonjour", sv: "god morgon", ru: "доброе утро", it: "buongiorno" },
        { cesky: "dobrý den", en: "good afternoon", de: "guten tag", es: "buenas tardes", nl: "goedendag", fr: "bonjour", sv: "god dag", ru: "добрый день", it: "buongiorno" },
        { cesky: "dobrou noc", en: "good night", de: "gute nacht", es: "buenas noches", nl: "goedenacht", fr: "bonne nuit", sv: "god natt", ru: "спокойной ночи", it: "buonanotte" },
        { cesky: "na shledanou", en: "goodbye", de: "auf wiedersehen", es: "adiós", nl: "tot ziens", fr: "au revoir", sv: "hej då", ru: "до свидания", it: "arrivederci" },
        { cesky: "prosím", en: "please", de: "bitte", es: "por favor", nl: "alstublieft", fr: "s'il vous plaît", sv: "snälla", ru: "пожалуйста", it: "per favore" },
        { cesky: "děkuji", en: "thank you", de: "danke", es: "gracias", nl: "dank u", fr: "merci", sv: "tack", ru: "спасибо", it: "grazie" },
        { cesky: "promiňte", en: "excuse me", de: "entschuldigung", es: "disculpe", nl: "pardon", fr: "excusez-moi", sv: "ursäkta", ru: "извините", it: "scusa" },
        { cesky: "jak se máš", en: "how are you", de: "wie geht es dir", es: "cómo estás", nl: "hoe gaat het", fr: "comment ça va", sv: "hur mår du", ru: "как дела", it: "come stai" },
        { cesky: "ano", en: "yes", de: "ja", es: "sí", nl: "ja", fr: "oui", sv: "ja", ru: "да", it: "sì" }
    ],
    rodina: [
        { cesky: "matka", en: "mother", de: "mutter", es: "madre", nl: "moeder", fr: "mère", sv: "mamma", ru: "мать", it: "madre" },
        { cesky: "otec", en: "father", de: "vater", es: "padre", nl: "vader", fr: "père", sv: "pappa", ru: "отец", it: "padre" },
        { cesky: "syn", en: "son", de: "sohn", es: "hijo", nl: "zoon", fr: "fils", sv: "son", ru: "сын", it: "figlio" },
        { cesky: "dcera", en: "daughter", de: "tochter", es: "hija", nl: "dochter", fr: "fille", sv: "dotter", ru: "дочь", it: "figlia" },
        { cesky: "dědeček", en: "grandfather", de: "großvater", es: "abuelo", nl: "grootvader", fr: "grand-père", sv: "morfar", ru: "дедушка", it: "nonno" },
        { cesky: "babička", en: "grandmother", de: "großmutter", es: "abuela", nl: "grootmoeder", fr: "grand-mère", sv: "mormor", ru: "бабушка", it: "nonna" },
        { cesky: "teta", en: "aunt", de: "tante", es: "tía", nl: "tante", fr: "tante", sv: "faster", ru: "тетя", it: "zia" },
        { cesky: "strýc", en: "uncle", de: "onkel", es: "tío", nl: "oom", fr: "oncle", sv: "farbror", ru: "дядя", it: "zio" },
        { cesky: "vnuk", en: "grandson", de: "enkel", es: "nieto", nl: "kleinzoon", fr: "petit-fils", sv: "barnbarn", ru: "внук", it: "nipote" },
        { cesky: "vnučka", en: "granddaughter", de: "enkelin", es: "nieta", nl: "kleindochter", fr: "petite-fille", sv: "barnbarn", ru: "внучка", it: "nipote" },
        { cesky: "bratr", en: "brother", de: "bruder", es: "hermano", nl: "broer", fr: "frère", sv: "bror", ru: "брат", it: "fratello" },
        { cesky: "sestra", en: "sister", de: "schwester", es: "hermana", nl: "zus", fr: "sœur", sv: "syster", ru: "сестра", it: "sorella" },
        { cesky: "sourozenec", en: "sibling", de: "geschwister", es: "hermano", nl: "broer of zus", fr: "frère ou sœur", sv: "syskon", ru: "родной брат", it: "fratello" }
    ],
    casti_tela: [
        { cesky: "hlava", en: "head", de: "kopf", es: "cabeza", nl: "hoofd", fr: "tête", sv: "huvud", ru: "голова", it: "testa" },
        { cesky: "oko", en: "eye", de: "auge", es: "ojo", nl: "oog", fr: "œil", sv: "öga", ru: "глаз", it: "occhio" },
        { cesky: "ucho", en: "ear", de: "ohr", es: "oreja", nl: "oor", fr: "oreille", sv: "öra", ru: "ухо", it: "orecchio" },
        { cesky: "nos", en: "nose", de: "nase", es: "nariz", nl: "neus", fr: "nez", sv: "näsa", ru: "нос", it: "naso" },
        { cesky: "ústa", en: "mouth", de: "mund", es: "boca", nl: "mond", fr: "bouche", sv: "mun", ru: "рот", it: "bocca" },
        { cesky: "ruka", en: "hand", de: "hand", es: "mano", nl: "hand", fr: "main", sv: "hand", ru: "рука", it: "mano" },
        { cesky: "noha", en: "leg", de: "bein", es: "pierna", nl: "been", fr: "jambe", sv: "ben", ru: "нога", it: "gamba" },
        { cesky: "paže", en: "arm", de: "arm", es: "brazo", nl: "arm", fr: "bras", sv: "arm", ru: "рука", it: "braccio" },
        { cesky: "chodidlo", en: "foot", de: "fuß", es: "pie", nl: "voet", fr: "pied", sv: "fot", ru: "стопа", it: "piede" },
        { cesky: "prst", en: "finger", de: "finger", es: "dedo", nl: "vinger", fr: "doigt", sv: "finger", ru: "палец", it: "dito" }
    ],
    vlastnosti_tela: [
        { cesky: "malý", en: "small", de: "klein", es: "pequeño", nl: "klein", fr: "petit", sv: "liten", ru: "маленький", it: "piccolo" },
        { cesky: "velký", en: "big", de: "groß", es: "grande", nl: "groot", fr: "grand", sv: "stor", ru: "большой", it: "grande" },
        { cesky: "dlouhý", en: "long", de: "lang", es: "largo", nl: "lang", fr: "long", sv: "lång", ru: "длинный", it: "lungo" },
        { cesky: "tlustý", en: "fat", de: "dick", es: "gordo", nl: "dik", fr: "gros", sv: "tjock", ru: "толстый", it: "grasso" },
        { cesky: "štíhlý", en: "slim", de: "schlank", es: "delgado", nl: "slank", fr: "mince", sv: "smal", ru: "стройный", it: "snello" },
        { cesky: "plešatý", en: "bald", de: "glatzköpfig", es: "calvo", nl: "kaal", fr: "chauve", sv: "skallig", ru: "лысый", it: "calvo" },
        { cesky: "mladý", en: "young", de: "jung", es: "joven", nl: "jong", fr: "jeune", sv: "ung", ru: "молодой", it: "giovane" },
        { cesky: "starý", en: "old", de: "alt", es: "viejo", nl: "oud", fr: "vieux", sv: "gammal", ru: "старый", it: "vecchio" }
    ],
    mistnosti_v_dome: [
        { cesky: "pokoj", en: "room", de: "zimmer", es: "habitación", nl: "kamer", fr: "chambre", sv: "rum", ru: "комната", it: "stanza" },
        { cesky: "záchod", en: "toilet", de: "toilette", es: "váter", nl: "toilet", fr: "toilette", sv: "toalett", ru: "туалет", it: "water" },
        { cesky: "koupelna", en: "bathroom", de: "badezimmer", es: "baño", nl: "badkamer", fr: "salle de bain", sv: "badrum", ru: "ванная", it: "bagno" },
        { cesky: "kuchyně", en: "kitchen", de: "küche", es: "cocina", nl: "keuken", fr: "cuisine", sv: "kök", ru: "кухня", it: "cucina" },
        { cesky: "předsíň", en: "hallway", de: "diele", es: "recibidor", nl: "hal", fr: "entrée", sv: "hall", ru: "прихожая", it: "ingresso" },
        { cesky: "garáž", en: "garage", de: "garage", es: "garaje", nl: "garage", fr: "garage", sv: "garage", ru: "гараж", it: "garage" },
        { cesky: "chodba", en: "corridor", de: "flur", es: "pasillo", nl: "gang", fr: "couloir", sv: "korridor", ru: "коридор", it: "corridoio" },
        { cesky: "sklep", en: "cellar", de: "keller", es: "sótano", nl: "kelder", fr: "cave", sv: "källare", ru: "подвал", it: "cantina" },
        { cesky: "obývák", en: "living room", de: "wohnzimmer", es: "salón", nl: "woonkamer", fr: "salon", sv: "vardagsrum", ru: "гостиная", it: "salotto" },
        { cesky: "jídelna", en: "dining room", de: "esszimmer", es: "comedor", nl: "eetkamer", fr: "salle à manger", sv: "matsal", ru: "столовая", it: "sala da pranzo" }
    ],
    zakladni_budovy: [
        { cesky: "škola", en: "school", de: "schule", es: "escuela", nl: "school", fr: "école", sv: "skola", ru: "школа", it: "scuola" },
        { cesky: "nemocnice", en: "hospital", de: "krankenhaus", es: "hospital", nl: "ziekenhuis", fr: "hôpital", sv: "sjukhus", ru: "больница", it: "ospedale" },
        { cesky: "nádraží", en: "station", de: "bahnhof", es: "estación", nl: "station", fr: "gare", sv: "station", ru: "вокзал", it: "stazione" },
        { cesky: "radnice", en: "town hall", de: "rathaus", es: "ayuntamiento", nl: "stadhuis", fr: "mairie", sv: "stadshus", ru: "ратуша", it: "municipio" },
        { cesky: "letiště", en: "airport", de: "flughafen", es: "aeropuerto", nl: "luchthaven", fr: "aéroport", sv: "flygplats", ru: "аэропорт", it: "aeroporto" },
        { cesky: "divadlo", en: "theatre", de: "theater", es: "teatro", nl: "theater", fr: "théâtre", sv: "teater", ru: "театр", it: "teatro" },
        { cesky: "kino", en: "cinema", de: "kino", es: "cine", nl: "bioscoop", fr: "cinéma", sv: "bio", ru: "кинотеатр", it: "cinema" },
        { cesky: "náměstí", en: "square", de: "platz", es: "plaza", nl: "plein", fr: "place", sv: "torg", ru: "площадь", it: "piazza" },
        { cesky: "obchod", en: "shop", de: "geschäft", es: "tienda", nl: "winkel", fr: "magasin", sv: "affär", ru: "магазин", it: "negozio" }
    ],
    pocasi: [
        { cesky: "slunce", en: "sun", de: "sonne", es: "sol", nl: "zon", fr: "soleil", sv: "sol", ru: "солнце", it: "sole" },
        { cesky: "déšť", en: "rain", de: "regen", es: "lluvia", nl: "regen", fr: "pluie", sv: "regn", ru: "дождь", it: "pioggia" },
        { cesky: "zataženo", en: "cloudy", de: "bewölkt", es: "nublado", nl: "bewolkt", fr: "nuageux", sv: "molnigt", ru: "облачно", it: "nuvoloso" },
        { cesky: "sníh", en: "snow", de: "schnee", es: "nieve", nl: "sneeuw", fr: "neige", sv: "snö", ru: "снег", it: "neve" },
        { cesky: "vítr", en: "wind", de: "wind", es: "viento", nl: "wind", fr: "vent", sv: "vind", ru: "ветер", it: "vento" },
        { cesky: "bouřka", en: "storm", de: "gewitter", es: "tormenta", nl: "storm", fr: "orage", sv: "storm", ru: "гроза", it: "tempesta" },
        { cesky: "zima", en: "cold", de: "kälte", es: "frío", nl: "koude", fr: "froid", sv: "kyla", ru: "холод", it: "freddo" },
        { cesky: "teplo", en: "warm", de: "wärme", es: "calor", nl: "warmte", fr: "chaud", sv: "värme", ru: "тепло", it: "caldo" },
        { cesky: "horko", en: "hot", de: "hitze", es: "caluroso", nl: "heet", fr: "brûlant", sv: "hetta", ru: "жара", it: "caldo" },
        { cesky: "chladno", en: "chilly", de: "kühl", es: "fresco", nl: "fris", fr: "frais", sv: "kylig", ru: "прохладно", it: "fresco" }
    ],
    konicky_a_sporty: [
        { cesky: "fotbal", en: "football", de: "fußball", es: "fútbol", nl: "voetbal", fr: "football", sv: "fotboll", ru: "футбол", it: "calcio" },
        { cesky: "tenis", en: "tennis", de: "tennis", es: "tenis", nl: "tennis", fr: "tennis", sv: "tennis", ru: "теннис", it: "tennis" },
        { cesky: "plavání", en: "swimming", de: "schwimmen", es: "natación", nl: "zwemmen", fr: "natation", sv: "simning", ru: "плавание", it: "nuoto" },
        { cesky: "běh", en: "running", de: "laufen", es: "carrera", nl: "hardlopen", fr: "courir", sv: "löpning", ru: "бег", it: "corsa" },
        { cesky: "cyklistika", en: "cycling", de: "radfahren", es: "ciclismo", nl: "fietsen", fr: "cyclisme", sv: "cykling", ru: "велоспорт", it: "ciclismo" },
        { cesky: "muzika", en: "music", de: "musik", es: "música", nl: "muziek", fr: "musique", sv: "musik", ru: "музыка", it: "musica" },
        { cesky: "filmy", en: "movies", de: "filme", es: "películas", nl: "films", fr: "films", sv: "filmer", ru: "фильмы", it: "film" },
        { cesky: "čtení", en: "reading", de: "lesen", es: "lectura", nl: "lezen", fr: "lecture", sv: "läsning", ru: "чтение", it: "lettura" }
    ],
    dopravni_prostredky: [
        { cesky: "auto", en: "car", de: "auto", es: "coche", nl: "auto", fr: "voiture", sv: "bil", ru: "машина", it: "automobile" },
        { cesky: "autobus", en: "bus", de: "bus", es: "autobús", nl: "bus", fr: "bus", sv: "buss", ru: "автобус", it: "autobus" },
        { cesky: "vlak", en: "train", de: "zug", es: "tren", nl: "trein", fr: "train", sv: "tåg", ru: "поезд", it: "treno" },
        { cesky: "kolo", en: "bicycle", de: "fahrrad", es: "bicicleta", nl: "fiets", fr: "vélo", sv: "cykel", ru: "велосипед", it: "bicicletta" },
        { cesky: "letadlo", en: "plane", de: "flugzeug", es: "avión", nl: "vliegtuig", fr: "avion", sv: "flygplan", ru: "самолет", it: "aereo" },
        { cesky: "motorka", en: "motorbike", de: "motorrad", es: "moto", nl: "motorfiets", fr: "moto", sv: "motorcykel", ru: "мотоцикл", it: "moto" }
    ],
    jidlo: [
        { cesky: "jablko", en: "apple", de: "apfel", es: "manzana", nl: "appel", fr: "pomme", sv: "äpple", ru: "яблоко", it: "mela" },
        { cesky: "banán", en: "banana", de: "banane", es: "plátano", nl: "banaan", fr: "banane", sv: "banan", ru: "банан", it: "banana" },
        { cesky: "pomeranč", en: "orange", de: "orange", es: "naranja", nl: "sinaasappel", fr: "orange", sv: "apelsin", ru: "апельсин", it: "arancia" },
        { cesky: "jahoda", en: "strawberry", de: "erdbeere", es: "fresa", nl: "aardbei", fr: "fraise", sv: "jordgubbe", ru: "клубника", it: "fragola" },
        { cesky: "citrón", en: "lemon", de: "zitrone", es: "limón", nl: "citroen", fr: "citron", sv: "citron", ru: "лимон", it: "limone" },
        { cesky: "hroznové víno", en: "grapes", de: "trauben", es: "uvas", nl: "druiven", fr: "raisins", sv: "druvor", ru: "виноград", it: "uva" },
        { cesky: "broskev", en: "peach", de: "pfirsich", es: "melocotón", nl: "perzik", fr: "pêche", sv: "persika", ru: "персик", it: "pesca" },
        { cesky: "hruška", en: "pear", de: "birne", es: "pera", nl: "peer", fr: "poire", sv: "päron", ru: "груша", it: "pera" },
        { cesky: "rajče", en: "tomato", de: "tomate", es: "tomate", nl: "tomaat", fr: "tomate", sv: "tomat", ru: "помидор", it: "pomodoro" },
        { cesky: "brambor", en: "potato", de: "kartoffel", es: "patata", nl: "aardappel", fr: "pomme de terre", sv: "potatis", ru: "картошка", it: "patata" },
        { cesky: "mrkev", en: "carrot", de: "karotte", es: "zanahoria", nl: "wortel", fr: "carotte", sv: "morot", ru: "морковь", it: "carota" },
        { cesky: "cibule", en: "onion", de: "zwiebel", es: "cebolla", nl: "ui", fr: "oignon", sv: "lök", ru: "лук", it: "cipolla" },
        { cesky: "česnek", en: "garlic", de: "knoblauch", es: "ajo", nl: "knoflook", fr: "ail", sv: "vitlök", ru: "чеснок", it: "aglio" },
        { cesky: "paprika", en: "pepper", de: "paprika", es: "pimiento", nl: "paprika", fr: "poivron", sv: "paprika", ru: "перец", it: "peperone" },
        { cesky: "mleko", en: "milk", de: "milch", es: "leche", nl: "melk", fr: "lait", sv: "mjölk", ru: "молоко", it: "latte" },
        { cesky: "maso", en: "meat", de: "fleisch", es: "carne", nl: "vlees", fr: "viande", sv: "kött", ru: "мясо", it: "carne" },
        { cesky: "rýže", en: "rice", de: "reis", es: "arroz", nl: "rijst", fr: "riz", sv: "ris", ru: "рис", it: "riso" },
        { cesky: "chléb", en: "bread", de: "brot", es: "pan", nl: "brood", fr: "pain", sv: "bröd", ru: "хлеб", it: "pane" },
        { cesky: "salát", en: "salad", de: "salat", es: "ensalada", nl: "salade", fr: "salade", sv: "sallad", ru: "салат", it: "insalata" }
    ],
    osobni_udaje: [
        { cesky: "jméno", en: "name", de: "name", es: "nombre", nl: "naam", fr: "nom", sv: "namn", ru: "имя", it: "nome" },
        { cesky: "příjmení", en: "surname", de: "nachname", es: "apellido", nl: "achternaam", fr: "nom de famille", sv: "efternamn", ru: "фамилия", it: "cognome" },
        { cesky: "věk", en: "age", de: "alter", es: "edad", nl: "leeftijd", fr: "âge", sv: "ålder", ru: "возраст", it: "età" },
        { cesky: "jméno", en: "first name", de: "vorname", es: "nombre de pila", nl: "voornaam", fr: "prénom", sv: "förnamn", ru: "имя", it: "nome di battesimo" },
        { cesky: "adresa", en: "address", de: "adresse", es: "dirección", nl: "adres", fr: "adresse", sv: "adress", ru: "адрес", it: "indirizzo" }
    ],
    slovesa: [
        { cesky: "být", en: "be", de: "sein", es: "ser", nl: "zijn", fr: "être", sv: "vara", ru: "быть", it: "essere" },
        { cesky: "mít", en: "have", de: "haben", es: "tener", nl: "hebben", fr: "avoir", sv: "ha", ru: "иметь", it: "avere" },
        { cesky: "dělat", en: "do", de: "machen", es: "hacer", nl: "doen", fr: "faire", sv: "göra", ru: "делать", it: "fare" },
        { cesky: "jít", en: "go", de: "gehen", es: "ir", nl: "gaan", fr: "aller", sv: "gå", ru: "идти", it: "andare" },
        { cesky: "mluvit", en: "speak", de: "sprechen", es: "hablar", nl: "spreken", fr: "parler", sv: "tala", ru: "говорить", it: "parlare" },
        { cesky: "chtít", en: "want", de: "wollen", es: "querer", nl: "willen", fr: "vouloir", sv: "vilja", ru: "хотеть", it: "volere" },
        { cesky: "vědět", en: "know", de: "wissen", es: "saber", nl: "weten", fr: "savoir", sv: "veta", ru: "знать", it: "sapere" },
        { cesky: "myslet", en: "think", de: "denken", es: "pensar", nl: "denken", fr: "penser", sv: "tänka", ru: "думать", it: "pensare" },
        { cesky: "vidět", en: "see", de: "sehen", es: "ver", nl: "zien", fr: "voir", sv: "se", ru: "видеть", it: "vedere" },
        { cesky: "jíst", en: "eat", de: "essen", es: "comer", nl: "eten", fr: "manger", sv: "äta", ru: "есть", it: "mangiare" },
        { cesky: "pít", en: "drink", de: "trinken", es: "beber", nl: "drinken", fr: "boire", sv: "dricka", ru: "пить", it: "bere" },
        { cesky: "spát", en: "sleep", de: "schlafen", es: "dormir", nl: "slapen", fr: "dormir", sv: "sova", ru: "спать", it: "dormire" },
        { cesky: "číst", en: "read", de: "lesen", es: "leer", nl: "lezen", fr: "lire", sv: "läsa", ru: "читать", it: "leggere" },
        { cesky: "psát", en: "write", de: "schreiben", es: "escribir", nl: "schrijven", fr: "écrire", sv: "skriva", ru: "писать", it: "scrivere" },
        { cesky: "učit se", en: "learn", de: "lernen", es: "aprender", nl: "leren", fr: "apprendre", sv: "lära sig", ru: "учиться", it: "imparare" },
        { cesky: "pracovat", en: "work", de: "arbeiten", es: "trabajar", nl: "werken", fr: "travailler", sv: "arbeta", ru: "работать", it: "lavorare" },
        { cesky: "kupovat", en: "buy", de: "kaufen", es: "comprar", nl: "kopen", fr: "acheter", sv: "köpa", ru: "покупать", it: "comprare" },
        { cesky: "cestovat", en: "travel", de: "reisen", es: "viajar", nl: "reizen", fr: "voyager", sv: "resa", ru: "путешествовать", it: "viaggiare" },
        { cesky: "hrát", en: "play", de: "spielen", es: "jugar", nl: "spelen", fr: "jouer", sv: "spela", ru: "играть", it: "giocare" },
        { cesky: "žít", en: "live", de: "leben", es: "vivir", nl: "leven", fr: "vivre", sv: "leva", ru: "жить", it: "vivere" },
        { cesky: "milovat", en: "love", de: "lieben", es: "amar", nl: "liefhebben", fr: "aimer", sv: "älska", ru: "любить", it: "amare" },
        { cesky: "pomáhat", en: "help", de: "helfen", es: "ayudar", nl: "helpen", fr: "aider", sv: "hjälpa", ru: "помогать", it: "aiutare" },
        { cesky: "rozumět", en: "understand", de: "verstehen", es: "entender", nl: "begrijpen", fr: "comprendre", sv: "förstå", ru: "понимать", it: "capire" },
        { cesky: "čekat", en: "wait", de: "warten", es: "esperar", nl: "wachten", fr: "attendre", sv: "vänta", ru: "ждать", it: "aspettare" },
        { cesky: "hledat", en: "look for", de: "suchen", es: "buscar", nl: "zoeken", fr: "chercher", sv: "söka", ru: "искать", it: "cercare" },
        { cesky: "otevřít", en: "open", de: "öffnen", es: "abrir", nl: "openen", fr: "ouvrir", sv: "öppna", ru: "открывать", it: "aprire" },
        { cesky: "zavřít", en: "close", de: "schließen", es: "cerrar", nl: "sluiten", fr: "fermer", sv: "stänga", ru: "закрывать", it: "chiudere" },
        { cesky: "říkat", en: "say", de: "sagen", es: "decir", nl: "zeggen", fr: "dire", sv: "säga", ru: "сказать", it: "dire" },
        { cesky: "přijít", en: "come", de: "kommen", es: "venir", nl: "komen", fr: "venir", sv: "komma", ru: "приходить", it: "venire" },
        { cesky: "brát", en: "take", de: "nehmen", es: "tomar", nl: "nemen", fr: "prendre", sv: "ta", ru: "брать", it: "prendere" }
    ]
};