const centralniDatabaze = {
    barvy: [
        { cesky: "červená", en: "red", de: "rot", es: "rojo", nl: "rood", fr: "rouge", sv: "röd", ru: "красный", it: "rosso" },
        { cesky: "modrá", en: "blue", de: "blau", es: "azul", nl: "blauw", fr: "bleu", sv: "blå", ru: "синий", it: "blu" },
        { cesky: "zelená", en: "green", de: "grün", es: "verde", nl: "groen", fr: "vert", sv: "grön", ru: "зеленый", it: "verde" },
        { cesky: "žlutá", en: "yellow", de: "gelb", es: "amarillo", nl: "geel", fr: "jaune", sv: "gul", ru: "желтый", it: "giallo" },
        { cesky: "černá", en: "black", de: "schwarz", es: "negro", nl: "zwart", fr: "noir", sv: "svart", ru: "черный", it: "nero" },
        { cesky: "bílá", en: "white", de: "weiß", es: "blanco", nl: "wit", fr: "blanc", sv: "vit", ru: "белый", it: "bianco" },
        { cesky: "oranžová", en: "orange", de: "orange", es: "naranja", nl: "oranje", fr: "orange", sv: "orange", ru: "оранжевый", it: "arancione" },
        { cesky: "růžová", en: "pink", de: "rosa", es: "rosa", nl: "roze", fr: "rose", sv: "rosa", ru: "розовый", it: "rosa" },
        { cesky: "šedá", en: "grey", de: "grau", es: "gris", nl: "grijs", fr: "gris", sv: "grå", ru: "серый", it: "grigio" }
    ],
    cisla: [
        { cesky: "jedna", en: "one", de: "eins", es: "uno", nl: "één", fr: "un", sv: "ett", ru: "один", it: "uno" },
        { cesky: "dva", en: "two", de: "zwei", es: "dos", nl: "twee", fr: "deux", sv: "två", ru: "два", it: "due" },
        { cesky: "tři", en: "three", de: "drei", es: "tres", nl: "drie", fr: "trois", sv: "tre", ru: "три", it: "tre" },
        { cesky: "čtyři", en: "four", de: "vier", es: "cuatro", nl: "vier", fr: "quatre", sv: "fyra", ru: "четыре", it: "quattro" },
        { cesky: "pět", en: "five", de: "fünf", es: "cinco", nl: "vijf", fr: "cinq", sv: "fem", ru: "пять", it: "cinque" },
        { cesky: "šest", en: "six", de: "sechs", es: "seis", nl: "zes", fr: "six", sv: "sex", ru: "шесть", it: "sei" },
        { cesky: "sedm", en: "seven", de: "sieben", es: "siete", nl: "zeven", fr: "sept", sv: "sju", ru: "семь", it: "sette" },
        { cesky: "osm", en: "eight", de: "acht", es: "ocho", nl: "acht", fr: "huit", sv: "åtta", ru: "восемь", it: "otto" },
        { cesky: "devět", en: "nine", de: "neun", es: "nueve", nl: "negen", fr: "neuf", sv: "nio", ru: "девать", it: "nove" },
        { cesky: "deset", en: "ten", de: "zehn", es: "diez", nl: "tien", fr: "dix", sv: "tio", ru: "десять", it: "dieci" },
        { cesky: "jedenáct", en: "eleven", de: "elf", es: "once", nl: "elf", fr: "onze", sv: "elva", ru: "одиннадцать", it: "undici" },
        { cesky: "dvanáct", en: "twelve", de: "zwölf", es: "doce", nl: "twaalf", fr: "douze", sv: "tolv", ru: "двенадцать", it: "dodici" },
        { cesky: "třináct", en: "thirteen", de: "dreizehn", es: "trece", nl: "dertien", fr: "treize", sv: "tretton", ru: "тринадцать", it: "tredici" },
        { cesky: "čtrnáct", en: "fourteen", de: "vierzehn", es: "catorce", nl: "veertien", fr: "quatorze", sv: "fjorton", ru: "четырнадцать", it: "quattordici" },
        { cesky: "patnáct", en: "fifteen", de: "fünfzehn", es: "quince", nl: "vijftien", fr: "quinze", sv: "femton", ru: "пятнадцать", it: "quindici" },
        { cesky: "šestnáct", en: "sixteen", de: "sechzehn", es: "diecisiete", nl: "zestien", fr: "seize", sv: "sexton", ru: "шестнадцать", it: "sedici" },
        { cesky: "sedmnáct", en: "seventeen", de: "siebzehn", es: "diecisiete", nl: "zeventien", fr: "dix-sept", sv: "sjutton", ru: "семнадцать", it: "diciassette" },
        { cesky: "osmnáct", en: "eighteen", de: "achtzehn", es: "dieciocho", nl: "achtien", fr: "dix-huit", sv: "arton", ru: "восемнадцать", it: "diciotto" },
        { cesky: "devatenáct", en: "nineteen", de: "neunzehn", es: "diecinueve", nl: "negentien", fr: "dix-neuf", sv: "nitton", ru: "девятнадцать", it: "diciannove" },
        { cesky: "dvacet", en: "twenty", de: "zwanzig", es: "veinte", nl: "twintig", fr: "vingt", sv: "tjugo", ru: "двадцать", it: "venti" },
        { cesky: "sto", en: "hundred", de: "hundert", es: "cien", nl: "honderd", fr: "cent", sv: "hundra", ru: "сто", it: "cento" },
        { cesky: "tisíc", en: "thousand", de: "tausend", es: "mil", nl: "duizend", fr: "mille", sv: "tusen", ru: "тысяча", it: "mille" }
    ],
    dny_v_tydnu: [
        { cesky: "pondělí", en: "monday", de: "montag", es: "lunes", nl: "maandag", fr: "lundi", sv: "måndag", ru: "понедельник", it: "lunedì" },
        { cesky: "úterý", en: "tuesday", de: "dienstag", es: "martes", nl: "dinsdag", fr: "mardi", sv: "tisdag", ru: "вторник", it: "martedì" },
        { cesky: "středa", en: "wednesday", de: "mittwoch", es: "miércoles", nl: "woensdag", fr: "mercredi", sv: "onsdag", ru: "среда", it: "mercoledì" },
        { cesky: "čtvrtek", en: "thursday", de: "donnerstag", es: "jueves", nl: "donderdag", fr: "jeudi", sv: "torsdag", ru: "четверг", it: "giovedì" },
        { cesky: "pátek", en: "friday", de: "freitag", es: "viernes", nl: "vrijdag", fr: "vendredi", sv: "fredag", ru: "пятница", it: "venerdì" },
        { cesky: "sobota", en: "saturday", de: "samstag", es: "sábado", nl: "zaterdag", fr: "samedi", sv: "lördag", ru: "суббота", it: "sabato" },
        { cesky: "neděle", en: "sunday", de: "sonntag", es: "domingo", nl: "zondag", fr: "dimanche", sv: "söndag", ru: "воскресенье", it: "domenica" }
    ],
    mesice: [
        { cesky: "leden", en: "january", de: "januar", es: "enero", nl: "januari", fr: "janvier", sv: "januari", ru: "январь", it: "gennaio" },
        { cesky: "únor", en: "february", de: "februar", es: "febrero", nl: "februari", fr: "février", sv: "februari", ru: "февраль", it: "febbraio" },
        { cesky: "březen", en: "march", de: "märz", es: "marzo", nl: "maart", fr: "mars", sv: "mars", ru: "март", it: "marzo" },
        { cesky: "duben", en: "april", de: "april", es: "abril", nl: "april", fr: "avril", sv: "april", ru: "апрель", it: "aprile" },
        { cesky: "květen", en: "may", de: "mai", es: "mayo", nl: "mei", fr: "mai", sv: "maj", ru: "май", it: "maggio" },
        { cesky: "červen", en: "june", de: "juni", es: "junio", nl: "juni", fr: "juin", sv: "juni", ru: "июнь", it: "giugno" },
        { cesky: "červenec", en: "july", de: "juli", es: "julio", nl: "juli", fr: "juillet", sv: "juli", ru: "июль", it: "luglio" },
        { cesky: "srpen", en: "august", de: "august", es: "agosto", nl: "augustus", fr: "août", sv: "augusti", ru: "август", it: "agosto" },
        { cesky: "září", en: "september", de: "september", es: "septiembre", nl: "september", fr: "septembre", sv: "september", ru: "сентябрь", it: "settembre" },
        { cesky: "říjen", en: "october", de: "oktober", es: "octubre", nl: "oktober", fr: "octobre", sv: "oktober", ru: "октябрь", it: "ottobre" },
        { cesky: "listopad", en: "november", de: "november", es: "noviembre", nl: "november", fr: "novembre", sv: "november", ru: "ноябрь", it: "novembre" },
        { cesky: "prosinec", en: "december", de: "dezember", es: "diciembre", nl: "december", fr: "décembre", sv: "december", ru: "декабрь", it: "dicembre" }
    ],
    zakladni_fraze: [
        { cesky: "ahoj", en: "hello", de: "hallo", es: "hola", nl: "hallo", fr: "salut", sv: "hej", ru: "привет", it: "ciao" },
        { cesky: "dobré ráno", en: "good morning", de: "guten morgen", es: "buenos días", nl: "goedemorgen", fr: "bonjour", sv: "god morgon", ru: "доброе утро", it: "buongiorno" },
        { cesky: "dobrý den", en: "good afternoon", de: "guten tag", es: "buenas tardes", nl: "goedendag", fr: "bonjour", sv: "god dag", ru: "добрый день", it: "buongiorno" },
        { cesky: "dobrou noc", en: "good night", de: "gute nacht", es: "buenas noches", nl: "goedenacht", fr: "bonne nuit", sv: "god natt", ru: "спокойной ночи", it: "buonanotte" },
        { cesky: "na shledanou", en: "goodbye", de: "auf wiedersehen", es: "adiós", nl: "tot ziens", fr: "au revoir", sv: "hej då", ru: "до свидания", it: "arrivederci" },
        { cesky: "prosím", en: "please", de: "bitte", es: "por favor", nl: "alstublieft", fr: "s'il vous plaît", sv: "snälla", ru: "пожалуйста", it: "per favore" },
        { cesky: "děkuji", en: "thank you", de: "danke", es: "gracias", nl: "dank u", fr: "merci", sv: "tack", ru: "спасибо", it: "grazie" },
        { cesky: "promiňte", en: "excuse me", de: "entschuldigung", es: "disculpe", nl: "pardon", fr: "excusez-moi", sv: "ursäkta", ru: "извините", it: "scusa" },
        { cesky: "jak se máš", en: "how are you", de: "wie geht es dir", es: "cómo estás", nl: "hoe gaat het", fr: "comment ça va", sv: "hur mår du", ru: "как дела", it: "come stai" },
        { cesky: "ano", en: "yes", de: "ja", es: "sí", nl: "ja", fr: "oui", sv: "ja", ru: "да", it: "sì" }
    ],
    rodina: [
        { cesky: "matka", en: "mother", de: "mutter", es: "madre", nl: "moeder", fr: "mère", sv: "mamma", ru: "мать", it: "madre" },
        { cesky: "otec", en: "father", de: "vater", es: "padre", nl: "vader", fr: "père", sv: "pappa", ru: "отец", it: "padre" },
        { cesky: "syn", en: "son", de: "sohn", es: "hijo", nl: "zoon", fr: "fils", sv: "son", ru: "сын", it: "figlio" },
        { cesky: "dcera", en: "daughter", de: "tochter", es: "hija", nl: "dochter", fr: "fille", sv: "dotter", ru: "дочь", it: "figlia" },
        { cesky: "dědeček", en: "grandfather", de: "großvater", es: "abuelo", nl: "grootvader", fr: "grand-père", sv: "morfar", ru: "дедушка", it: "nonno" },
        { cesky: "babička", en: "grandmother", de: "großmutter", es: "abuela", nl: "grootmoeder", fr: "grand-mère", sv: "mormor", ru: "бабушка", it: "nonna" },
        { cesky: "teta", en: "aunt", de: "tante", es: "tía", nl: "tante", fr: "tante", sv: "faster", ru: "тетя", it: "zia" },
        { cesky: "strýc", en: "uncle", de: "onkel", es: "tío", nl: "oom", fr: "oncle", sv: "farbror", ru: "дядя", it: "zio" },
        { cesky: "vnuk", en: "grandson", de: "enkel", es: "nieto", nl: "kleinzoon", fr: "petit-fils", sv: "barnbarn", ru: "внук", it: "nipote" },
        { cesky: "vnučka", en: "granddaughter", de: "enkelin", es: "nieta", nl: "kleindochter", fr: "petite-fille", sv: "barnbarn", ru: "внучка", it: "nipote" },
        { cesky: "bratr", en: "brother", de: "bruder", es: "hermano", nl: "broer", fr: "frère", sv: "bror", ru: "брат", it: "fratello" },
        { cesky: "sestra", en: "sister", de: "schwester", es: "hermana", nl: "zus", fr: "sœur", sv: "syster", ru: "сестра", it: "sorella" },
        { cesky: "sourozenec", en: "sibling", de: "geschwister", es: "hermano", nl: "broer of zus", fr: "frère ou sœur", sv: "syskon", ru: "родной брат", it: "fratello" }
    ],
    casti_tela: [
        { cesky: "hlava", en: "head", de: "kopf", es: "cabeza", nl: "hoofd", fr: "tête", sv: "huvud", ru: "голова", it: "testa" },
        { cesky: "oko", en: "eye", de: "auge", es: "ojo", nl: "oog", fr: "œil", sv: "öga", ru: "глаз", it: "occhio" },
        { cesky: "ucho", en: "ear", de: "ohr", es: "oreja", nl: "oor", fr: "oreille", sv: "öra", ru: "ухо", it: "orecchio" },
        { cesky: "nos", en: "nose", de: "nase", es: "nariz", nl: "neus", fr: "nez", sv: "näsa", ru: "нос", it: "naso" },
        { cesky: "ústa", en: "mouth", de: "mund", es: "boca", nl: "mond", fr: "bouche", sv: "mun", ru: "рот", it: "bocca" },
        { cesky: "ruka", en: "hand", de: "hand", es: "mano", nl: "hand", fr: "main", sv: "hand", ru: "рука", it: "mano" },
        { cesky: "noha", en: "leg", de: "bein", es: "pierna", nl: "been", fr: "jambe", sv: "ben", ru: "нога", it: "gamba" },
        { cesky: "paže", en: "arm", de: "arm", es: "brazo", nl: "arm", fr: "bras", sv: "arm", ru: "рука", it: "braccio" },
        { cesky: "chodidlo", en: "foot", de: "fuß", es: "pie", nl: "voet", fr: "pied", sv: "fot", ru: "стопа", it: "piede" },
        { cesky: "prst", en: "finger", de: "finger", es: "dedo", nl: "vinger", fr: "doigt", sv: "finger", ru: "палец", it: "dito" }
    ],
    vlastnosti_tela: [
        { cesky: "malý", en: "small", de: "klein", es: "pequeño", nl: "klein", fr: "petit", sv: "liten", ru: "маленький", it: "piccolo" },
        { cesky: "velký", en: "big", de: "groß", es: "grande", nl: "groot", fr: "grand", sv: "stor", ru: "большой", it: "grande" },
        { cesky: "dlouhý", en: "long", de: "lang", es: "largo", nl: "lang", fr: "long", sv: "lång", ru: "длинный", it: "lungo" },
        { cesky: "tlustý", en: "fat", de: "dick", es: "gordo", nl: "dik", fr: "gros", sv: "tjock", ru: "толстый", it: "grasso" },
        { cesky: "štíhlý", en: "slim", de: "schlank", es: "delgado", nl: "slank", fr: "mince", sv: "smal", ru: "стройный", it: "snello" },
        { cesky: "plešatý", en: "bald", de: "glatzköpfig", es: "calvo", nl: "kaal", fr: "chauve", sv: "skallig", ru: "лысый", it: "calvo" },
        { cesky: "mladý", en: "young", de: "jung", es: "joven", nl: "jong", fr: "jeune", sv: "ung", ru: "молодой", it: "giovane" },
        { cesky: "starý", en: "old", de: "alt", es: "viejo", nl: "oud", fr: "vieux", sv: "gammal", ru: "старый", it: "vecchio" }
    ],
    mistnosti_v_dome: [
        { cesky: "pokoj", en: "room", de: "zimmer", es: "habitación", nl: "kamer", fr: "chambre", sv: "rum", ru: "комната", it: "stanza" },
        { cesky: "záchod", en: "toilet", de: "toilette", es: "váter", nl: "toilet", fr: "toilette", sv: "toalett", ru: "туалет", it: "water" },
        { cesky: "koupelna", en: "bathroom", de: "badezimmer", es: "baño", nl: "badkamer", fr: "salle de bain", sv: "badrum", ru: "ванная", it: "bagno" },
        { cesky: "kuchyně", en: "kitchen", de: "küche", es: "cocina", nl: "keuken", fr: "cuisine", sv: "kök", ru: "кухня", it: "cucina" },
        { cesky: "předsíň", en: "hallway", de: "diele", es: "recibidor", nl: "hal", fr: "entrée", sv: "hall", ru: "прихожая", it: "ingresso" },
        { cesky: "garáž", en: "garage", de: "garage", es: "garaje", nl: "garage", fr: "garage", sv: "garage", ru: "гараж", it: "garage" },
        { cesky: "chodba", en: "corridor", de: "flur", es: "pasillo", nl: "gang", fr: "couloir", sv: "korridor", ru: "коридор", it: "corridoio" },
        { cesky: "sklep", en: "cellar", de: "keller", es: "sótano", nl: "kelder", fr: "cave", sv: "källare", ru: "подвал", it: "cantina" },
        { cesky: "obývák", en: "living room", de: "wohnzimmer", es: "salón", nl: "woonkamer", fr: "salon", sv: "vardagsrum", ru: "гостиная", it: "salotto" },
        { cesky: "jídelna", en: "dining room", de: "esszimmer", es: "comedor", nl: "eetkamer", fr: "salle à manger", sv: "matsal", ru: "столовая", it: "sala da pranzo" }
    ],
    zakladni_budovy: [
        { cesky: "škola", en: "school", de: "schule", es: "escuela", nl: "school", fr: "école", sv: "skola", ru: "школа", it: "scuola" },
        { cesky: "nemocnice", en: "hospital", de: "krankenhaus", es: "hospital", nl: "ziekenhuis", fr: "hôpital", sv: "sjukhus", ru: "больница", it: "ospedale" },
        { cesky: "nádraží", en: "station", de: "bahnhof", es: "estación", nl: "station", fr: "gare", sv: "station", ru: "вокзал", it: "stazione" },
        { cesky: "radnice", en: "town hall", de: "rathaus", es: "ayuntamiento", nl: "stadhuis", fr: "mairie", sv: "stadshus", ru: "ратуша", it: "municipio" },
        { cesky: "letiště", en: "airport", de: "flughafen", es: "aeropuerto", nl: "luchthaven", fr: "aéroport", sv: "flygplats", ru: "аэропорт", it: "aeroporto" },
        { cesky: "divadlo", en: "theatre", de: "theater", es: "teatro", nl: "theater", fr: "théâtre", sv: "teater", ru: "театр", it: "teatro" },
        { cesky: "kino", en: "cinema", de: "kino", es: "cine", nl: "bioscoop", fr: "cinéma", sv: "bio", ru: "кинотеатр", it: "cinema" },
        { cesky: "náměstí", en: "square", de: "platz", es: "plaza", nl: "plein", fr: "place", sv: "torg", ru: "площадь", it: "piazza" },
        { cesky: "obchod", en: "shop", de: "geschäft", es: "tienda", nl: "winkel", fr: "magasin", sv: "affär", ru: "магазин", it: "negozio" }
    ],
    pocasi: [
        { cesky: "slunce", en: "sun", de: "sonne", es: "sol", nl: "zon", fr: "soleil", sv: "sol", ru: "солнце", it: "sole" },
        { cesky: "déšť", en: "rain", de: "regen", es: "lluvia", nl: "regen", fr: "pluie", sv: "regn", ru: "дождь", it: "pioggia" },
        { cesky: "zataženo", en: "cloudy", de: "bewölkt", es: "nublado", nl: "bewolkt", fr: "nuageux", sv: "molnigt", ru: "облачно", it: "nuvoloso" },
        { cesky: "sníh", en: "snow", de: "schnee", es: "nieve", nl: "sneeuw", fr: "neige", sv: "snö", ru: "снег", it: "neve" },
        { cesky: "vítr", en: "wind", de: "wind", es: "viento", nl: "wind", fr: "vent", sv: "vind", ru: "ветер", it: "vento" },
        { cesky: "bouřka", en: "storm", de: "gewitter", es: "tormenta", nl: "storm", fr: "orage", sv: "storm", ru: "гроза", it: "tempesta" },
        { cesky: "zima", en: "cold", de: "kälte", es: "frío", nl: "koude", fr: "froid", sv: "kyla", ru: "холод", it: "freddo" },
        { cesky: "teplo", en: "warm", de: "wärme", es: "calor", nl: "warmte", fr: "chaud", sv: "värme", ru: "тепло", it: "caldo" },
        { cesky: "horko", en: "hot", de: "hitze", es: "caluroso", nl: "heet", fr: "brûlant", sv: "hetta", ru: "жара", it: "caldo" },
        { cesky: "chladno", en: "chilly", de: "kühl", es: "fresco", nl: "fris", fr: "frais", sv: "kylig", ru: "прохладно", it: "fresco" }
    ],
    konicky_a_sporty: [
        { cesky: "fotbal", en: "football", de: "fußball", es: "fútbol", nl: "voetbal", fr: "football", sv: "fotboll", ru: "футбол", it: "calcio" },
        { cesky: "tenis", en: "tennis", de: "tennis", es: "tenis", nl: "tennis", fr: "tennis", sv: "tennis", ru: "теннис", it: "tennis" },
        { cesky: "plavání", en: "swimming", de: "schwimmen", es: "natación", nl: "zwemmen", fr: "natation", sv: "simning", ru: "плавание", it: "nuoto" },
        { cesky: "běh", en: "running", de: "laufen", es: "carrera", nl: "hardlopen", fr: "courir", sv: "löpning", ru: "бег", it: "corsa" },
        { cesky: "cyklistika", en: "cycling", de: "radfahren", es: "ciclismo", nl: "fietsen", fr: "cyclisme", sv: "cykling", ru: "велоспорт", it: "ciclismo" },
        { cesky: "muzika", en: "music", de: "musik", es: "música", nl: "muziek", fr: "musique", sv: "musik", ru: "музыка", it: "musica" },
        { cesky: "filmy", en: "movies", de: "filme", es: "películas", nl: "films", fr: "films", sv: "filmer", ru: "фильмы", it: "film" },
        { cesky: "čtení", en: "reading", de: "lesen", es: "lectura", nl: "lezen", fr: "lecture", sv: "läsning", ru: "чтение", it: "lettura" }
    ],
    dopravni_prostredky: [
        { cesky: "auto", en: "car", de: "auto", es: "coche", nl: "auto", fr: "voiture", sv: "bil", ru: "машина", it: "automobile" },
        { cesky: "autobus", en: "bus", de: "bus", es: "autobús", nl: "bus", fr: "bus", sv: "buss", ru: "автобус", it: "autobus" },
        { cesky: "vlak", en: "train", de: "zug", es: "tren", nl: "trein", fr: "train", sv: "tåg", ru: "поезд", it: "treno" },
        { cesky: "kolo", en: "bicycle", de: "fahrrad", es: "bicicleta", nl: "fiets", fr: "vélo", sv: "cykel", ru: "велосипед", it: "bicicletta" },
        { cesky: "letadlo", en: "plane", de: "flugzeug", es: "avión", nl: "vliegtuig", fr: "avion", sv: "flygplan", ru: "самолет", it: "aereo" },
        { cesky: "motorka", en: "motorbike", de: "motorrad", es: "moto", nl: "motorfiets", fr: "moto", sv: "motorcykel", ru: "мотоцикл", it: "moto" }
    ],
    jidlo: [
        { cesky: "jablko", en: "apple", de: "apfel", es: "manzana", nl: "appel", fr: "pomme", sv: "äpple", ru: "яблоко", it: "mela" },
        { cesky: "banán", en: "banana", de: "banane", es: "plátano", nl: "banaan", fr: "banane", sv: "banan", ru: "банан", it: "banana" },
        { cesky: "pomeranč", en: "orange", de: "orange", es: "naranja", nl: "sinaasappel", fr: "orange", sv: "apelsin", ru: "апельсин", it: "arancia" },
        { cesky: "jahoda", en: "strawberry", de: "erdbeere", es: "fresa", nl: "aardbei", fr: "fraise", sv: "jordgubbe", ru: "клубника", it: "fragola" },
        { cesky: "citrón", en: "lemon", de: "zitrone", es: "limón", nl: "citroen", fr: "citron", sv: "citron", ru: "лимон", it: "limone" },
        { cesky: "hroznové víno", en: "grapes", de: "trauben", es: "uvas", nl: "druiven", fr: "raisins", sv: "druvor", ru: "виноград", it: "uva" },
        { cesky: "broskev", en: "peach", de: "pfirsich", es: "melocotón", nl: "perzik", fr: "pêche", sv: "persika", ru: "персик", it: "pesca" },
        { cesky: "hruška", en: "pear", de: "birne", es: "pera", nl: "peer", fr: "poire", sv: "päron", ru: "груша", it: "pera" },
        { cesky: "rajče", en: "tomato", de: "tomate", es: "tomate", nl: "tomaat", fr: "tomate", sv: "tomat", ru: "помидор", it: "pomodoro" },
        { cesky: "brambor", en: "potato", de: "kartoffel", es: "patata", nl: "aardappel", fr: "pomme de terre", sv: "potatis", ru: "картошка", it: "patata" },
        { cesky: "mrkev", en: "carrot", de: "karotte", es: "zanahoria", nl: "wortel", fr: "carotte", sv: "morot", ru: "морковь", it: "carota" },
        { cesky: "cibule", en: "onion", de: "zwiebel", es: "cebolla", nl: "ui", fr: "oignon", sv: "lök", ru: "лук", it: "cipolla" },
        { cesky: "česnek", en: "garlic", de: "knoblauch", es: "ajo", nl: "knoflook", fr: "ail", sv: "vitlök", ru: "чеснок", it: "aglio" },
        { cesky: "paprika", en: "pepper", de: "paprika", es: "pimiento", nl: "paprika", fr: "poivron", sv: "paprika", ru: "перец", it: "peperone" },
        { cesky: "mleko", en: "milk", de: "milch", es: "leche", nl: "melk", fr: "lait", sv: "mjölk", ru: "молоко", it: "latte" },
        { cesky: "maso", en: "meat", de: "fleisch", es: "carne", nl: "vlees", fr: "viande", sv: "kött", ru: "мясо", it: "carne" },
        { cesky: "rýže", en: "rice", de: "reis", es: "arroz", nl: "rijst", fr: "riz", sv: "ris", ru: "рис", it: "riso" },
        { cesky: "chléb", en: "bread", de: "brot", es: "pan", nl: "brood", fr: "pain", sv: "bröd", ru: "хлеб", it: "pane" },
        { cesky: "salát", en: "salad", de: "salat", es: "ensalada", nl: "salade", fr: "salade", sv: "sallad", ru: "салат", it: "insalata" }
    ],
    osobni_udaje: [
        { cesky: "jméno", en: "name", de: "name", es: "nombre", nl: "naam", fr: "nom", sv: "namn", ru: "имя", it: "nome" },
        { cesky: "příjmení", en: "surname", de: "nachname", es: "apellido", nl: "achternaam", fr: "nom de famille", sv: "efternamn", ru: "фамилия", it: "cognome" },
        { cesky: "věk", en: "age", de: "alter", es: "edad", nl: "leeftijd", fr: "âge", sv: "ålder", ru: "возраст", it: "età" },
        { cesky: "jméno", en: "first name", de: "vorname", es: "nombre de pila", nl: "voornaam", fr: "prénom", sv: "förnamn", ru: "имя", it: "nome di battesimo" },
        { cesky: "adresa", en: "address", de: "adresse", es: "dirección", nl: "adres", fr: "adresse", sv: "adress", ru: "адрес", it: "indirizzo" }
    ],
    slovesa: [
       
  { cesky: "být", en: "be", de: "sein", es: "ser", nl: "zijn", fr: "être", sv: "vara", ru: "быть", it: "essere" },
  { cesky: "mít", en: "have", de: "haben", es: "tener", nl: "hebben", fr: "avoir", sv: "ha", ru: "иметь", it: "avere" },
  { cesky: "stát se", en: "become", de: "werden", es: "llegar a ser", nl: "worden", fr: "devenir", sv: "bli", ru: "стать", it: "diventare" },
  { cesky: "moci / umět", en: "can / be able to", de: "können", es: "poder", nl: "kunnen", fr: "pouvoir", sv: "kan / kunna", ru: "мочь", it: "potere" },
  { cesky: "muset", en: "must / have to", de: "müssen", es: "tener que", nl: "moeten", fr: "devoir", sv: "måste", ru: "должен", it: "dovere" },
  { cesky: "smět", en: "be allowed to", de: "dürfen", es: "poder (permiso)", nl: "mogen", fr: "avoir le droit de", sv: "få", ru: "иметь разрешение", it: "avere il permesso" },
  { cesky: "chtít", en: "want", de: "wollen", es: "querer", nl: "willen", fr: "vouloir", sv: "vilja", ru: "хотеть", it: "volere" },
  { cesky: "mít povinnost / dělati (měl by)", en: "should / ought to", de: "sollen", es: "deber", nl: "horen te", fr: "devoir", sv: "bör / böra", ru: "следовать", it: "dovere" },
  { cesky: "mít rád", en: "like", de: "mögen", es: "gustar", nl: "houden van", fr: "aimer", sv: "gilla", ru: "любить / нравиться", it: "piacere" },
  { cesky: "chtěl by", en: "would like", de: "möchten", es: "gustaría", nl: "zouden willen", fr: "aimerait", sv: "skulle vilja", ru: "хотел бы", it: "vorrebbe" },
  { cesky: "dělat", en: "do / make", de: "machen", es: "hacer", nl: "maken / doen", fr: "faire", sv: "göra", ru: "делать", it: "fare" },
  { cesky: "jít / kráčet", en: "go / walk", de: "gehen", es: "ir", nl: "gaan / lopen", fr: "aller / marcher", sv: "gå", ru: "идти / ходить", it: "andare / camminare" },
  { cesky: "přijít", en: "come", de: "kommen", es: "venir", nl: "komen", fr: "venir", sv: "komma", ru: "прийти / приходить", it: "venire" },
  { cesky: "jet / cestovat", en: "drive / ride", de: "fahren", es: "conducir / ir en vehículo", nl: "rijden", fr: "conduire / aller en véhicule", sv: "köra / åka", ru: "ехать / вести", it: "guidare / andare in veicolo" },
  { cesky: "vidět", en: "see", de: "sehen", es: "ver", nl: "zien", fr: "voir", sv: "se", ru: "видеть", it: "vedere" },
  { cesky: "číst", en: "read", de: "lesen", es: "leer", nl: "lezen", fr: "lire", sv: "läsa", ru: "читать", it: "leggere" },
  { cesky: "psát", en: "write", de: "schreiben", es: "escribir", nl: "schrijven", fr: "écrire", sv: "skriva", ru: "писать", it: "scrivere" },
  { cesky: "mluvit", en: "speak / talk", de: "sprechen", es: "hablar", nl: "spreken / praten", fr: "parler", sv: "tala / prata", ru: "говорить", it: "parlare" },
  { cesky: "jíst", en: "eat", de: "essen", es: "comer", nl: "eten", fr: "manger", sv: "äta", ru: "есть", it: "mangiare" },
  { cesky: "pít", en: "drink", de: "trinken", es: "beber", nl: "drinken", fr: "boire", sv: "dricka", ru: "пить", it: "bere" },
  { cesky: "spát", en: "sleep", de: "schlafen", es: "dormir", nl: "slapen", fr: "dormir", sv: "sova", ru: "спать", it: "dormire" },
  { cesky: "pracovat", en: "work", de: "arbeiten", es: "trabajar", nl: "werken", fr: "travailler", sv: "arbeta / jobba", ru: "работать", it: "lavorare" },
  { cesky: "bydlet", en: "live / reside", de: "wohnen", es: "vivir / residir", nl: "wonen", fr: "habiter", sv: "bo", ru: "жить / проживать", it: "abitare" },
  { cesky: "koupit", en: "buy", de: "kaufen", es: "comprar", nl: "kopen", fr: "acheter", sv: "köpa", ru: "купить / покупать", it: "comprare" },
  { cesky: "dát / dát něco někomu", en: "give", de: "geben", es: "dar", nl: "geven", fr: "donner", sv: "ge", ru: "дать / давать", it: "dare" },
  { cesky: "vzít", en: "take", de: "nehmen", es: "tomar / coger", nl: "nemen", fr: "prendre", sv: "ta", ru: "взять / брать", it: "prendere" },
  { cesky: "pomoci", en: "help", de: "helfen", es: "ayudar", nl: "helpen", fr: "aider", sv: "hjälpa", ru: "помочь / помогать", it: "aiutare" },
  { cesky: "najít", en: "find", de: "finden", es: "encontrar", nl: "vinden", fr: "trouver", sv: "hitta", ru: "найти / находить", it: "trovare" },
  { cesky: "myslet", en: "think", de: "denken", es: "pensar", nl: "denken", fr: "penser", sv: "tänka", ru: "думать", it: "pensare" },
  { cesky: "vědět", en: "know (facts)", de: "wissen", es: "saber", nl: "weten", fr: "savoir", sv: "veta", ru: "знать", it: "sapere" },
  { cesky: "znát", en: "know (person/place)", de: "kennen", es: "conocer", nl: "kennen", fr: "connaître", sv: "känna", ru: "знать (кого/что)", it: "conoscere" },
  { cesky: "říkat / sdělit", en: "say / tell", de: "sagen", es: "decir", nl: "zeggen", fr: "dire", sv: "säga", ru: "сказать / говорить", it: "dire" },
  { cesky: "ptát se", en: "ask", de: "fragen", es: "preguntar", nl: "vragen", fr: "demander", sv: "fråga", ru: "спрашивать", it: "chiedere" },
  { cesky: "odpovědět", en: "answer", de: "antworten", es: "responder", nl: "antwoorden", fr: "répondre", sv: "svara", ru: "ответить / отвечать", it: "rispondere" },
  { cesky: "děkovat", en: "thank", de: "danken", es: "agradecer", nl: "bedanken", fr: "remercier", sv: "tacka", ru: "благодарить", it: "ringraziare" },
  { cesky: "běžet", en: "run", de: "laufen", es: "correr", nl: "rennen / lopen", fr: "courir", sv: "springa", ru: "бежать / бегать", it: "correre" },
  { cesky: "létat", en: "fly", de: "fliegen", es: "volar", nl: "vliegen", fr: "voler", sv: "flyga", ru: "летать / лететь", it: "volare" },
  { cesky: "zůstat", en: "stay / remain", de: "bleiben", es: "quedarse / permanecer", nl: "blijven", fr: "rester", sv: "stanna", ru: "остаться / оставаться", it: "rimanere / restare" },
  { cesky: "potkat / setkat se", en: "meet", de: "treffen", es: "encontrar / quedar", nl: "ontmoeten", fr: "rencontrer", sv: "träffa", ru: "встретить / встречаться", it: "incontrare" },
  { cesky: "přinést", en: "bring", de: "bringen", es: "traer", nl: "brengen", fr: "apporter", sv: "ta med / bringa", ru: "принести / приносить", it: "portare" },
  { cesky: "nosit / mít na sobě", en: "wear / carry", de: "tragen", es: "llevar / vestir", nl: "dragen", fr: "porter", sv: "bära / ha på sig", ru: "носить", it: "portare / indossare" },
  { cesky: "zapomenout", en: "forget", de: "vergessen", es: "olvidar", nl: "vergeten", fr: "oublier", sv: "glömma", ru: "забыть / забывать", it: "dimenticare" },
  { cesky: "ztratit", en: "lose", de: "verlieren", es: "perder", nl: "verliezen", fr: "perdre", sv: "förlora / tappa", ru: "потерять / терять", it: "perdere" },
  { cesky: "platit", en: "pay", de: "bezahlen", es: "pagar", nl: "betalen", fr: "payer", sv: "betala", ru: "платить", it: "pagare" },
  { cesky: "platit / stát (o ceně)", en: "cost", de: "kosten", es: "costar", nl: "kosten", fr: "coûter", sv: "kosta", ru: "стоить", it: "costare" },
  { cesky: "učit se", en: "learn / study", de: "lernen", es: "aprender", nl: "leren", fr: "apprendre", sv: "lära sig", ru: "учиться / учить", it: "imparare" },
  { cesky: "studovat (na VŠ)", en: "study", de: "studieren", es: "estudiar", nl: "studeren", fr: "étudier", sv: "studera", ru: "учиться (в ВУЗе)", it: "studiare" },
  { cesky: "hrát", en: "play", de: "spielen", es: "jugar / tocar", nl: "spelen", fr: "jouer", sv: "spela", ru: "играть", it: "giocare / suonare" },
  { cesky: "slyšet", en: "hear", de: "hören", es: "oír / escuchar", nl: "horen", fr: "entendre", sv: "höra", ru: "слышать", it: "sentire" },
  { cesky: "poslouchat", en: "listen", de: "zuhören", es: "escuchar", nl: "luisteren", fr: "écouter", sv: "lyssna", ru: "слушать", it: "ascoltare" },
  { cesky: "vařit", en: "cook", de: "kochen", es: "cocinar", nl: "koken", fr: "cuisiner", sv: "laga mat", ru: "готовить", it: "cucinare" },
  { cesky: "pečení / péct", en: "bake", de: "backen", es: "hornear", nl: "bakken", fr: "cuire au four", sv: "baka", ru: "печь / выпекать", it: "cuocere al forno" },
  { cesky: "žít", en: "live", de: "leben", es: "vivir", nl: "leven", fr: "vivre", sv: "leva", ru: "жить", it: "vivere" },
  { cesky: "mít rád / milovat", en: "love", de: "lieben", es: "amar", nl: "liefhebben", fr: "aimer", sv: "älska", ru: "любить", it: "amare" },
  { cesky: "smát se", en: "laugh", de: "lachen", es: "reír", nl: "lachen", fr: "rire", sv: "skratta", ru: "смеяться", it: "ridere" },
  { cesky: "plakat", en: "cry", de: "weinen", es: "llorar", nl: "huilen", fr: "pleurer", sv: "gråta", ru: "плакать", it: "piangere" },
  { cesky: "čekat", en: "wait", de: "warten", es: "esperar", nl: "wachten", fr: "attendre", sv: "vänta", ru: "ждать", it: "aspettare" },
  { cesky: "hledat", en: "search / look for", de: "suchen", es: "buscar", nl: "zoeken", fr: "chercher", sv: "söka / leta", ru: "искать", it: "cercare" },
  { cesky: "potřebovat", en: "need", de: "brauchen", es: "necesitar", nl: "nodig hebben", fr: "avoir besoin de", sv: "behöva", ru: "нуждаться", it: "aver bisogno di" },
  { cesky: "věřit", en: "believe", de: "glauben", es: "creer", nl: "geloven", fr: "croire", sv: "tro", ru: "верить", it: "credere" },
  { cesky: "doufat", en: "hope", de: "hoffen", es: "esperar (tener esperanza)", nl: "hopen", fr: "espérer", sv: "hoppas", ru: "надеяться", it: "sperare" },
  { cesky: "přát si", en: "wish", de: "wünschen", es: "desear", nl: "wensen", fr: "souhaiter", sv: "önska", ru: "желать", it: "desiderare" },
  { cesky: "ukázat", en: "show", de: "zeigen", es: "mostrar / enseñar", nl: "tonen / laten zien", fr: "montrer", sv: "visa", ru: "показать / показывать", it: "mostrare" },
  { cesky: "vysvětlit", en: "explain", de: "erklären", es: "explicar", nl: "uitleggen", fr: "expliquer", sv: "förklara", ru: "объяснить / объяснять", it: "spiegare" },
  { cesky: "rozumět", en: "understand", de: "verstehen", es: "entender", nl: "begrijpen", fr: "comprendre", sv: "förstå", ru: "понимать", it: "capire" },
  { cesky: "znamenat", en: "mean", de: "bedeuten", es: "significar", nl: "betekenen", fr: "signifier", sv: "betyda", ru: "значить / означать", it: "significare" },
  { cesky: "otevřít", en: "open", de: "öffnen", es: "abrir", nl: "openen", fr: "ouvrir", sv: "öppna", ru: "открыть / открывать", it: "aprire" },
  { cesky: "zavřít", en: "close", de: "schließen", es: "cerrar", nl: "sluiten", fr: "fermer", sv: "stänga", ru: "закрыть / закрывать", it: "chiudere" },
  { cesky: "začít", en: "begin", de: "beginnen", es: "empezar", nl: "beginnen", fr: "commencer", sv: "börja", ru: "начать / начинать", it: "cominciare / iniziare" },
  { cesky: "končit", en: "end / finish", de: "enden", es: "terminar", nl: "eindigen", fr: "terminer", sv: "sluta", ru: "кончать / заканчивать", it: "finire / terminare" },
  { cesky: "přestat", en: "stop", de: "aufhören", es: "parar / dejar de", nl: "stoppen", fr: "arrêter", sv: "sluta / stanna", ru: "прекратить / перестать", it: "smettere" },
  { cesky: "sedět", en: "sit", de: "sitzen", es: "estar sentado", nl: "zitten", fr: "être assis", sv: "sitta", ru: "сидеть", it: "sedere / essere seduto" },
  { cesky: "posadit se", en: "sit down", de: "sich setzen", es: "sentarse", nl: "gaan zitten", fr: "s'asseoir", sv: "sätta sig", ru: "сесть / садиться", it: "sedersi" },
  { cesky: "stát", en: "stand", de: "stehen", es: "estar de pie", nl: "staan", fr: "être debout", sv: "stå", ru: "стоять", it: "stare in piedi" },
  { cesky: "postavit", en: "put / set up", de: "stellen", es: "poner de pie", nl: "neerzetten", fr: "poser / placer", sv: "ställa", ru: "поставить / ставить", it: "mettere in piedi" },
  { cesky: "ležet", en: "lie", de: "liegen", es: "estar tumbado", nl: "liggen", fr: "être allongé", sv: "ligga", ru: "лежать", it: "giacere / essere sdraiato" },
  { cesky: "položit", en: "lay / put down", de: "legen", es: "poner en horizontal", nl: "neerleggen", fr: "poser", sv: "lägga", ru: "положить / класть", it: "posare / mettere" },
  { cesky: "viset", en: "hang", de: "hängen", es: "colgar / estar colgado", nl: "hangen", fr: "être accroché", sv: "hänga", ru: "висеть", it: "pendere / essere appeso" },
  { cesky: "pověsit", en: "hang up", de: "aufhängen", es: "colgar", nl: "ophangen", fr: "accrocher", sv: "hänga upp", ru: "повесить / вешать", it: "appendere" },
  { cesky: "sahat / dát", en: "put / place", de: "stecken", es: "meter / poner", nl: "steken / stoppen", fr: "mettre / insérer", sv: "stoppa / stoppa in", ru: "сунуть / сувать", it: "infilare / mettere" },
  { cesky: "padat / padnout", en: "fall", de: "fallen", es: "caer", nl: "vallen", fr: "tomber", sv: "falla / ramla", ru: "падать / упасть", it: "cadere" },
  { cesky: "skákat", en: "jump", de: "springen", es: "saltar", nl: "springen", fr: "sauter", sv: "hoppa", ru: "прыгать", it: "saltare" },
  { cesky: "plavat", en: "swim", de: "schwimmen", es: "nadar", nl: "zwemmen", fr: "nager", sv: "simma", ru: "плавать", it: "nuotare" },
  { cesky: "tančit", en: "dance", de: "tanzen", es: "bailar", nl: "dansen", fr: "danser", sv: "dansa", ru: "танцевать", it: "ballare" },
  { cesky: "zpívat", en: "sing", de: "singen", es: "cantar", nl: "zingen", fr: "chanter", sv: "sjunga", ru: "петь", it: "cantare" },
  { cesky: "malovat / kreslit", en: "paint / draw", de: "malen", es: "pintar / dibujar", nl: "schilderen", fr: "peindre", sv: "måla", ru: "рисовать", it: "dipingere" },
  { cesky: "kreslit", en: "draw", de: "zeichnen", es: "dibujar", nl: "tekenen", fr: "dessiner", sv: "rita", ru: "чертить / рисовать", it: "disegnare" },
  { cesky: "fotografovat", en: "photograph", de: "fotografieren", es: "fotografiar", nl: "fotograferen", fr: "photographier", sv: "fotografera", ru: "фотографировать", it: "fotografare" },
  { cesky: "cestovat", en: "travel", de: "reisen", es: "viajar", nl: "reizen", fr: "voyager", sv: "resa", ru: "путешествовать", it: "viaggiare" },
  { cesky: "balit", en: "pack", de: "packen", es: "empacar", nl: "inpakken", fr: "emballer / faire les bagages", sv: "packa", ru: "упаковывать / собирать", it: "fare le valigie" },
  { cesky: "mýt / prát", en: "wash", de: "waschen", es: "lavar", nl: "wassen", fr: "laver", sv: "tvätta", ru: "мыть / стирать", it: "lavare" },
  { cesky: "čistit", en: "clean", de: "putzen", es: "limpiar", nl: "schoonmaken", fr: "nettoyer", sv: "städa / rengöra", ru: "чистить", it: "pulire" },
  { cesky: "uklízet", en: "clean up", de: "aufräumen", es: "ordenar", nl: "opruimen", fr: "ranger", sv: "plocka undan", ru: "убирать", it: "riordinare" },
  { cesky: "sprchovat se", en: "shower", de: "duschen", es: "ducharse", nl: "douchen", fr: "se doucher", sv: "duscha", ru: "принимать душ", it: "farsi la doccia" },
  { cesky: "koupat se", en: "bathe", de: "baden", es: "bañarse", nl: "baden", fr: "se baigner", sv: "bada", ru: "купаться", it: "fare il bagno" },
  { cesky: "holit se", en: "shave", de: "rasieren", es: "afeitarse", nl: "scheren", fr: "se raser", sv: "raka sig", ru: "бриться", it: "rasarsi" },
  { cesky: "česat se", en: "comb", de: "kämmen", es: "peinarse", nl: "kammen", fr: "se meigner", sv: "kamma sig", ru: "причесываться", it: "pettinarsi" },
  { cesky: "oblékat se", en: "dress / put on", de: "anziehen", es: "vestirse", nl: "aankleden", fr: "s'habiller", sv: "klä på sig", ru: "одеваться", it: "vestirsi" },
  { cesky: "svlékat se", en: "undress", de: "ausziehen", es: "desvestirse", nl: "uitkleden", fr: "se déshabiller", sv: "klä av sig", ru: "раздеваться", it: "spogliarsi" },
  { cesky: "převlékat se", en: "change clothes", de: "umziehen", es: "cambiarse de ropa", nl: "omkleden", fr: "se changer", sv: "byta om", ru: "переодеваться", it: "cambiarsi d'abito" },
  { cesky: "nakupovat", en: "shop", de: "einkaufen", es: "comprar", nl: "winkelen / boodschappen doen", fr: "faire des courses", sv: "handla", ru: "делать покупки", it: "fare la spesa" },
  { cesky: "vstávat", en: "get up", de: "aufstehen", es: "levantarse", nl: "opstaan", fr: "se lever", sv: "stiga upp", ru: "вставать", it: "alzarsi" },
  { cesky: "zavolat (telefonem)", en: "call", de: "anrufen", es: "llamar", nl: "bellen", fr: "appeler", sv: "ringa", ru: "позвонить", it: "chiamare" },
  { cesky: "přijít / dorazit", en: "arrive", de: "ankommen", es: "llegar", nl: "aankomen", fr: "arriver", sv: "anlända / komma fram", ru: "прибывать / приезжать", it: "arrivare" },
  { cesky: "odjet", en: "depart", de: "abfahren", es: "salir (vehículo)", nl: "vertrekken", fr: "partir", sv: "åka iväg / avgå", ru: "уехать / отъезжать", it: "partire" },
  { cesky: "odletět", en: "depart (plane)", de: "abfliegen", es: "despegar", nl: "vliegen (vertrekken)", fr: "décoller", sv: "flyga iväg", ru: "вылетать", it: "decollare" },
  { cesky: "jít s někým / jít spolu", en: "come along", de: "mitkommen", es: "acompañar", nl: "meegaan", fr: "accompagner / venir avec", sv: "följa med", ru: "идти вместе", it: "andare insieme" },
  { cesky: "vznášet se / vzít s sebou", en: "take along", de: "mitnehmen", es: "llevar consigo", nl: "meenemen", fr: "emporter", sv: "ta med sig", ru: "брать с собой", it: "portare con sé" },
  { cesky: "přinést s sebou", en: "bring along", de: "mitbringen", es: "traer consigo", nl: "meebrengen", fr: "apporter", sv: "ta med sig hit", ru: "приносить с собой", it: "portare con sé" },
  { cesky: "díval se na TV", en: "watch TV", de: "fernsehen", es: "ver la televisión", nl: "tv-kijken", fr: "regarder la télé", sv: "titta på tv", ru: "смотреть телевизор", it: "guardare la tv" },
  { cesky: "vypadat", en: "look like / appear", de: "aussehen", es: "parecer", nl: "eruitzien", fr: "avoir l'air / ressembler", sv: "se ut", ru: "выглядеть", it: "sembrare / apparire" },
  { cesky: "představit se / představit si", en: "introduce / imagine", de: "vorstellen", es: "presentar / imaginar", nl: "voorstellen", fr: "se présenter / imaginer", sv: "presentera / föreställa sig", ru: "представиться / представить", it: "presentarsi / immaginare" },
  { cesky: "připravit", en: "prepare", de: "vorbereiten", es: "preparar", nl: "voorbereiden", fr: "préparer", sv: "förbereda", ru: "приготовить / подготавливать", it: "preparare" },
  { cesky: "začít (opět)", en: "start", de: "anfangen", es: "empezar", nl: "beginnen", fr: "commencer", sv: "börja", ru: "начинать", it: "iniziare" },
  { cesky: "nabídnout", en: "offer", de: "anbieten", es: "ofrecer", nl: "aanbieden", fr: "offrir", sv: "erbjuda", ru: "предложить / предлагать", it: "offrire" },
  { cesky: "přijmout", en: "accept", de: "annehmen", es: "aceptar", nl: "accepteren / aannemen", fr: "accepter", sv: "acceptera / ta emot", ru: "принять / принимать", it: "accettare" },
  { cesky: "přestoupit (doprava)", en: "change trains", de: "umsteigen", es: "cambiar de tren/autobús", nl: "overstappen", fr: "changer de train/bus", sv: "byta tåg/buss", ru: "делать пересадку", it: "cambiare treno/bus" },
  { cesky: "nastoupit", en: "get in", de: "einsteigen", es: "subir a un vehículo", nl: "instappen", fr: "monter dans un véhicule", sv: "stiga på", ru: "садиться в транспорт", it: "salire su un veicolo" },
  { cesky: "vystoupit", en: "get out", de: "aussteigen", es: "bajar de un vehículo", nl: "uitstappen", fr: "descendre d'un véhicule", sv: "stiga av", ru: "выходить из транспорта", it: "scendere da un veicolo" },
  { cesky: "pozvat", en: "invite", de: "einladen", es: "invitar", nl: "uitnodigen", fr: "inviter", sv: "bjuda in", ru: "пригласить / приглашать", it: "invitare" },
  { cesky: "doporučit", en: "recommend", de: "empfehlen", es: "recomendar", nl: "aanbevelen", fr: "recommander", sv: "rekommendera", ru: "рекомендовать", it: "raccomandare" },
  { cesky: "obdržet / dostat", en: "receive / get", de: "bekommen", es: "recibir / obtener", nl: "krijgen / ontvangen", fr: "recevoir / obtenir", sv: "få / ta emot", ru: "получить / получать", it: "ricevere / ottenere" },
  { cesky: "zapomenout", en: "forget", de: "vergessen", es: "olvidar", nl: "vergeten", fr: "oublier", sv: "glömma", ru: "забыть", it: "dimenticare" },
  { cesky: "prohrát / ztratit", en: "lose", de: "verlieren", es: "perder", nl: "verliezen", fr: "perdre", sv: "förlora", ru: "проиграть / потерять", it: "perdere" },
  { cesky: "pronajmout", en: "rent", de: "vermieten", es: "alquilar (dar en alquiler)", nl: "verhuren", fr: "louer (à quelqu'un)", sv: "hyra ut", ru: "сдавать в аренду", it: "affittare (dare in affitto)" },
  { cesky: "najmout si", en: "rent", de: "mieten", es: "alquilar (tomar en alquiler)", nl: "huren", fr: "louer (prendre en location)", sv: "hyra", ru: "арендовать / снимать", it: "noleggiare / affittare" },
  { cesky: "prodat", en: "sell", de: "verkaufen", es: "vender", nl: "verkopen", fr: "vendre", sv: "sälja", ru: "продать / продавать", it: "vendere" },
  { cesky: "platit", en: "pay", de: "bezahlen", es: "pagar", nl: "betalen", fr: "payer", sv: "betala", ru: "платить", it: "pagare" },
  { cesky: "platit / vyplatit", en: "pay", de: "zahlen", es: "pagar", nl: "betalen", fr: "payer", sv: "betala", ru: "оплачивать", it: "pagare" },
  { cesky: "popsat", en: "describe", de: "beschreiben", es: "describir", nl: "beschrijven", fr: "décrire", sv: "beskriva", ru: "описать / описывать", it: "descrivere" },
  { cesky: "navštívit", en: "visit", de: "besuchen", es: "visitar", nl: "bezoeken", fr: "rendre visite / visiter", sv: "besöka", ru: "посетить / навещать", it: "visitare" },
  { cesky: "prohlédnout si", en: "visit / view", de: "besichtigen", es: "visitar / contemplar", nl: "bezichtigen", fr: "visiter (un lieu)", sv: "beskåda / besöka", ru: "осматривать", it: "visitare (un luogo)" },
  { cesky: "objednat", en: "order", de: "bestellen", es: "pedir / encargar", nl: "bestellen", fr: "commander", sv: "beställa", ru: "заказать / заказыват", it: "ordinare" },
  { cesky: "nechat / dovolit", en: "let / allow", de: "lassen", es: "dejar / permitir", nl: "laten", fr: "laisser / permettre", sv: "låta", ru: "оставить / позволить", it: "lasciare / permettere" },
  { cesky: "držet", en: "hold", de: "halten", es: "sostener / parar", nl: "vasthouden", fr: "tenir", sv: "hålla", ru: "держать", it: "tenere" },
  { cesky: "srovnat / porovnat", en: "compare", de: "vergleichen", es: "comparar", nl: "vergelijken", fr: "comparer", sv: "jämföra", ru: "сравнить / сравнивать", it: "confrontare" },
  { cesky: "vyhrát", en: "win", de: "gewinnen", es: "ganar", nl: "winnen", fr: "gagner", sv: "vinna", ru: "выиграть / выигрывать", it: "vincere" },
  { cesky: "spadnout", en: "fall", de: "fallen", es: "caer", nl: "vallen", fr: "tomber", sv: "ramla / falla", ru: "упасть", it: "cadere" },
  { cesky: "rozhodnout", en: "decide", de: "entscheiden", es: "decidir", nl: "beslissen", fr: "décider", sv: "bestämma", ru: "решить / решать", it: "decidere" },
  { cesky: "stříhat / řezat", en: "cut", de: "schneiden", es: "cortar", nl: "snijden / knippen", fr: "couper", sv: "skära / klippa", ru: "резать / стричь", it: "tagliare" },
  { cesky: "spát", en: "sleep", de: "schlafen", es: "dormir", nl: "slapen", fr: "dormir", sv: "sova", ru: "спать", it: "dormire" },
  { cesky: "ublížit / bolet", en: "hurt", de: "weh tun", es: "doler", nl: "pijn doen", fr: "faire mal", sv: "göra ont", ru: "причинять боль / болеть", it: "fare male" },
  { cesky: "bít / udeřit", en: "hit / beat", de: "schlagen", es: "golpear", nl: "slaag / slaan", fr: "frapper", sv: "slå", ru: "бить / ударять", it: "colpire" },
  { cesky: "nést / nosit", en: "carry / wear", de: "tragen", es: "llevar", nl: "dragen", fr: "porter", sv: "bära", ru: "нести / носить", it: "portare" },
  { cesky: "stát (o ceně)", en: "cost", de: "kosten", es: "costar", nl: "kosten", fr: "coûter", sv: "kosta", ru: "стоить", it: "costare" },
  { cesky: "stáhnout / táhnout", en: "pull / move", de: "ziehen", es: "tirar / mudarse", nl: "trekken", fr: "tirer", sv: "dra", ru: "тянуть", it: "tirare" },
  { cesky: "stěhovat se", en: "move (house)", de: "umziehen", es: "mudarse", nl: "verhuizen", fr: "déménager", sv: "flytta", ru: "переезжать", it: "traslocare" },
  { cesky: "tlačit / strčit", en: "push", de: "schieben", es: "empujar", nl: "duwen", fr: "pousser", sv: "putsa / skjuta", ru: "толкать", it: "spingere" },
  { cesky: "házet", en: "throw", de: "werfen", es: "tirar / lanzar", nl: "gooien", fr: "jeter / lancer", sv: "kasta", ru: "бросать / кидать", it: "lanciare" },
  { cesky: "půjčit", en: "lend", de: "leihen", es: "prestar", nl: "uitlenen", fr: "prêter", sv: "låna ut", ru: "одолжить / давать вдолг", it: "prestare" },
  { cesky: "těšit se (na)", en: "look forward to", de: "sich freuen auf", es: "alegrarse de", nl: "uitkijken naar", fr: "se réjouir de", sv: "se fram emot", ru: "ждать с нетерпением", it: "non vedere l'ora di" },
  { cesky: "mít radost (z)", en: "be glad about", de: "sich freuen über", es: "alegrarse por", nl: "blij zijn met", fr: "être content de", sv: "vara glad över", ru: "радоваться", it: "essere felice per" },
  { cesky: "zajímat se (o)", en: "be interested in", de: "sich interessieren für", es: "interesarse por", nl: "geïnteresseerd zijn in", fr: "s'intéresser à", sv: "intressera sig för", ru: "интересоваться", it: "interessarsi a" },
  { cesky: "zlobit se (na)", en: "be angry with", de: "sich ärgern über", es: "enfadarse con", nl: "boos zijn op", fr: "être en colère contre", sv: "vara arg på", ru: "сердиться на", it: "arrabbiarsi con" },
  { cesky: "cítit se", en: "feel", de: "sich fühlen", es: "sentirse", nl: "zich voelen", fr: "se sentir", sv: "känna sig", ru: "чувствовать себя", it: "sentirsi" },
  { cesky: "omluvit se", en: "apologize", de: "sich entschuldigen", es: "disculparse", nl: "zich verontschuldigen", fr: "s'excuser", sv: "be om ursäkt", ru: "извиниться", it: "scusarsi" },
  { cesky: "stěžovat si", en: "complain", de: "sich beschweren", es: "quejarse", nl: "klagen", fr: "se plaindre", sv: "klaga", ru: "жаловаться", it: "lamentarsi" },
  { cesky: "všimnout si", en: "notice", de: "bemerken", es: "darse cuenta de", nl: "opmerken", fr: "remarquer", sv: "märka", ru: "заметить", it: "notare" },
  { cesky: "starat se (o)", en: "take care of", de: "sich kümmern um", es: "cuidar de", nl: "zorgen voor", fr: "s'occuper de", sv: "ta hand om", ru: "заботиться о", it: "occuparsi di" },
  { cesky: "pamatovat si / vzpomenout si", en: "remember", de: "sich erinnern an", es: "acordarse de", nl: "zich herinneren", fr: "se souvenir de", sv: "komma ihåg", ru: "помнить / вспомнить", it: "ricordarsi di" },
  { cesky: "soustředit se", en: "concentrate", de: "sich konzentrieren", es: "concentrarse", nl: "zich concentreren", fr: "se concentrer", sv: "koncentrera sig", ru: "сосредотачиваться", it: "concentrarsi" },
  { cesky: "odpočinout si", en: "relax / rest", de: "sich ausruhen", es: "descansar", nl: "uitrusten", fr: "se reposer", sv: "vila sig", ru: "отдохнуть", it: "riposarsi" },
  { cesky: "přihlásit se", en: "register / log in", de: "sich anmelden", es: "registrarse", nl: "zich aanmelden / inloggen", fr: "s'inscrire / se connecter", sv: "registrera sig / logga in", ru: "зарегистрироваться / войти", it: "registrarsi / accedere" },
  { cesky: "odhlásit se", en: "log out", de: "sich abmelden", es: "cerrar sesión", nl: "uitloggen", fr: "se déconnecter", sv: "logga ut", ru: "выйти из системы", it: "disconnettersi" },
  { cesky: "platit v hotovosti", en: "pay cash", de: "bar bezahlen", es: "pagar en efectivo", nl: "contant betalen", fr: "payer en espèces", sv: "betala kontant", ru: "платить наличными", it: "pagare in contanti" },
  { cesky: "vyměnit", en: "exchange", de: "tauschen", es: "cambiar", nl: "ruilen", fr: "échanger", sv: "byta", ru: "обменять / менять", it: "scambiare" },
  { cesky: "zarezervovat", en: "book / reserve", de: "buchen / reservieren", es: "reservar", nl: "reserveren", fr: "réserver", sv: "boka / reservera", ru: "забронировать", it: "prenotare" },
  { cesky: "zrušit / odvolat", en: "cancel", de: "absagen", es: "cancelar", nl: "annuleren", fr: "annuler", sv: "avboka / ställa in", ru: "отменить", it: "annullare" },
  { cesky: "potvrdit", en: "confirm", de: "bestätigen", es: "confirmar", nl: "bevestigen", fr: "confirmer", sv: "bekräfta", ru: "подтвердить", it: "confermare" },
  { cesky: "podepsat", en: "sign", de: "unterschreiben", es: "firmar", nl: "ondertekenen", fr: "signer", sv: "skriva under", ru: "подписать", it: "firmare" },
  { cesky: "vyplnit (formulář)", en: "fill in", de: "ausfüllen", es: "rellenar", nl: "invullen", fr: "remplir", sv: "fylla i", ru: "заполнить (форму)", it: "compilare" },
  { cesky: "poslat", en: "send", de: "schicken / senden", es: "enviar", nl: "sturen / verzenden", fr: "envoyer", sv: "skicka", ru: "послать / отправлять", it: "inviare / spedire" },
  { cesky: "obdržet", en: "receive", de: "erhalten", es: "recibir", nl: "ontvangen", fr: "recevoir", sv: "ta emot", ru: "получить", it: "ricevere" },
  { cesky: "předat", en: "hand over", de: "übergeben", es: "entregar", nl: "overhandigen", fr: "remettre", sv: "överlämna", ru: "передать", it: "consegnare" },
  { cesky: "vydělávat (peníze)", en: "earn (money)", de: "verdienen", es: "ganar (dinero)", nl: "verdiend", fr: "gagner (de l'argent)", sv: "tjäna (pengar)", ru: "зарабатывать", it: "guadagnare" },
  { cesky: "utrácet (peníze)", en: "spend (money)", de: "ausgeben", es: "gastar", nl: "uitgeven", fr: "dépenser", sv: "spendera", ru: "тратить", it: "spendere" },
  { cesky: "šetřit", en: "save (money)", de: "sparen", es: "ahorrar", nl: "sparen", fr: "économiser", sv: "spara", ru: "копить / экономить", it: "risparmiare" },
  { cesky: "darovat", en: "donate / give as gift", de: "schenken", es: "regalar", nl: "schenken / geven", fr: "offrir", sv: "skänka / ge bort", ru: "дарить", it: "donare / regalare" },
  { cesky: "letět", en: "fly", de: "fliegen", es: "volar", nl: "vliegen", fr: "voler", sv: "flyga", ru: "летать", it: "volare" },
  { cesky: "řídit (auto)", en: "drive", de: "steuern / fahren", es: "conducir", nl: "besturen / rijden", fr: "conduire", sv: "köra", ru: "водить (машину)", it: "guidare" },
  { cesky: "parkovat", en: "park", de: "parken", es: "aparcar", nl: "parkeren", fr: "garer / stationner", sv: "parkera", ru: "парковаться", it: "parcheggiare" },
  { cesky: "tankovat", en: "refuel", de: "tanken", es: "repostar", nl: "tanken", fr: "faire le plein", sv: "tanka", ru: "заправляться", it: "fare benzina" },
  { cesky: "zabloudit", en: "get lost", de: "sich verlaufen", es: "extraviarse", nl: "verdwalen", fr: "se perdre", sv: "gå vilse", ru: "заблудиться", it: "perdersi" },
  { cesky: "navštívit (lékaře)", en: "consult / visit", de: "aufsuchen", es: "consultar", nl: "raadplegen", fr: "consulter", sv: "uppsöka", ru: "обратиться к врачу", it: "consultare (un medico)" },
  { cesky: "vyšetřit", en: "examine", de: "untersuchen", es: "examinar", nl: "onderzoeken", fr: "examiner", sv: "undersöka", ru: "обследовать", it: "esaminare" },
  { cesky: "předepsat (lék)", en: "prescribe", de: "verschreiben", es: "recetar", nl: "voorschrijven", fr: "prescrire", sv: "förskriva", ru: "прописать (лекарство)", it: "prescrivere" },
  { cesky: "chybět", en: "miss / be absent", de: "fehlen", es: "faltar", nl: "ontbreken / missen", fr: "manquer", sv: "saknas", ru: "отсутствовать / не хватать", it: "mancare" },
  { cesky: "bolet", en: "ache / hurt", de: "schmerzen", es: "doler", nl: "pijn doen", fr: "faire mal", sv: "smärta", ru: "болеть", it: "doler" },
  { cesky: "uzdravit se", en: "recover", de: "gesund werden", es: "curarse", nl: "genezen", fr: "guérir", sv: "tillfriskna", ru: "выздороветь", it: "guarire" },
  { cesky: "slavit", en: "celebrate", de: "feiern", es: "celebrar", nl: "vieren", fr: "célébrer / fêter", sv: "fira", ru: "праздновать", it: "festeggiare" },
  { cesky: "bavit se / užívat si", en: "have fun", de: "Spaß haben", es: "divertirse", nl: "plezier hebben", fr: "s me amuser", sv: "ha roligt", ru: "веселиться", it: "divertirsi" },
  { cesky: "organizovat", en: "organize", de: "organisieren", es: "organizar", nl: "organiseren", fr: "organiser", sv: "organisera", ru: "организовать", it: "organizzare" },
  { cesky: "plánovat", en: "plan", de: "planen", es: "planificar", nl: "plannen", fr: "planifier", sv: "planera", ru: "планировать", it: "pianificare" },
  { cesky: "povídat si", en: "chat / talk", de: "sprechen / sich unterhalten", es: "charlar", nl: "kletsen / praten", fr: "bavarder", sv: "prata / småprata", ru: "болтать", it: "chiacchierare" },
  { cesky: "diskutovat", en: "discuss", de: "diskutieren", es: "discutir", nl: "discussiëren", fr: "discuter", sv: "diskutera", ru: "дискутировать", it: "discutere" },
  { cesky: "souhlasit", en: "agree", de: "zustimmen", es: "estar de acuerdo", nl: "akkoord gaan", fr: "être d'accord", sv: "hålla med", ru: "согласиться", it: "essere d'accordo" },
  { cesky: "nesouhlasit", en: "disagree", de: "widersprechen", es: "no estar de acuerdo", nl: "het niet eens zijn", fr: "ne pas être d'accord", sv: "hålla inte med", ru: "не соглашаться", it: "disaccordare" },
  { cesky: "sjet / myslet si", en: "think / opinion", de: "meinen", es: "opinar", nl: "vinden / menen", fr: "penser / être d'avis", sv: "mena / tycka", ru: "считать / полагать", it: "ritenere" },
  { cesky: "doporučit", en: "suggest", de: "vorschlagen", es: "proponer", nl: "voorstellen", fr: "suggérer", sv: "föreslå", ru: "предлагать", it: "suggerire" },
  { cesky: "rádit / poradit", en: "advise", de: "raten", es: "aconsejar", nl: "adviseren", fr: "conseiller", sv: "råda", ru: "советовать", it: "consigliare" },
  { cesky: "varovat", en: "warn", de: "warnen", es: "advertir", nl: "waarschuwen", fr: "avertir", sv: "varna", ru: "предупреждать", it: "avvertire" },
  { cesky: "slíbit", en: "promise", de: "versprechen", es: "prometer", nl: "beloven", fr: "promettre", sv: "lova", ru: "обещать", it: "promettere" },
  { cesky: "lhát", en: "lie", de: "lügen", es: "mentir", nl: "liegen", fr: "mentir", sv: "ljuga", ru: "врать / лгать", it: "mentire" },
  { cesky: "mlčet", en: "be silent", de: "schweigen", es: "callar", nl: "zwijgen", fr: "se taire", sv: "tiga", ru: "молчать", it: "tacere" },
  { cesky: "pršet", en: "rain", de: "regnen", es: "llover", nl: "regenen", fr: "pleuvoir", sv: "regna", ru: "идти (о дожде)", it: "piovere" },
  { cesky: "sněžit", en: "snow", de: "schneien", es: "nevar", nl: "sneeuwen", fr: "neiger", sv: "snöa", ru: "идти (о снеге)", it: "nevicare" },
  { cesky: "foukat (vítr)", en: "blow", de: "wehen / blasen", es: "soplar", nl: "waaien / blazen", fr: "souffler", sv: "blåsa", ru: "дуть", it: "soffiare" },
  { cesky: "svítit (slunce)", en: "shine", de: "scheinen", es: "brillar", nl: "schijnen", fr: "briller", sv: "skina", ru: "светить", it: "splendere" },
  { cesky: "stmívat se", en: "get dark", de: "dunkel werden", es: "anochecer", nl: "donker worden", fr: "faire nuit", sv: "mörkna", ru: "темнеть", it: "farsi buio" },
  { cesky: "mrazit", en: "freeze", de: "frieren", es: "helar", nl: "vriezen", fr: "geler", sv: "frysa", ru: "подмораживать", it: "gelare" },
  { cesky: "horořet / pálit", en: "burn", de: "brennen", es: "arder", nl: "branden", fr: "brûler", sv: "brinna", ru: "гореть", it: "bruciare" },
  { cesky: "vařit (voda)", en: "boil", de: "kochen", es: "hervir", nl: "koken", fr: "bouillir", sv: "koka", ru: "кипеть", it: "bollire" },
  { cesky: "smažit", en: "fry", de: "braten", es: "freír", nl: "bakken / braden", fr: "frire", sv: "steka", ru: "жарить", it: "friggere" },
  { cesky: "krájet", en: "slice / cut", de: "schneiden", es: "cortar", nl: "snijden", fr: "couper", sv: "skära", ru: "нарезать", it: "tagliare a fette" },
  { cesky: "míchat", en: "mix / stir", de: "mischen / rühren", es: "mezclar", nl: "mengen / roeren", fr: "mélanger", sv: "blanda / röra", ru: "мешать / смешивать", it: "mescolare" },
  { cesky: "prostřít (stůl)", en: "set (the table)", de: "den Tisch decken", es: "poner la mesa", nl: "de tafel dekken", fr: "mettre la table", sv: "duka bordet", ru: "накрывать на стол", it: "apparecchiare" },
  { cesky: "sklidit (ze stolu)", en: "clear (the table)", de: "den Tisch abräumen", es: "recoger la mesa", nl: "de tafel afruimen", fr: "débarrasser la table", sv: "duka av bordet", ru: "убирать со стола", it: "sparecchiare" },
  { cesky: "mýt nádobí", en: "wash dishes", de: "spülen / geschirr spülen", es: "fregar los platos", nl: "afwassen", fr: "faire la vaisselle", sv: "diska", ru: "мыть посуду", it: "lavare i piatti" },
  { cesky: "vysávat", en: "vacuum", de: "staubsaugen", es: "pasar la aspiradora", nl: "stofzuigen", fr: "passer l'aspirateur", sv: "dammsuga", ru: "пылесосить", it: "passare l'aspirapolvere" },
  { cesky: "žehlit", en: "iron", de: "bügeln", es: "planchar", nl: "strijken", fr: "repasser", sv: "stryka", ru: "гладить", it: "stirare" },
  { cesky: "opravit", en: "repair", de: "reparieren", es: "reparar", nl: "repareren", fr: "réparer", sv: "reparera", ru: "чинить / ремонтировать", it: "riparare" },
  { cesky: "fungovat", en: "work / function", de: "funktionieren", es: "funcionar", nl: "functioning / werken", fr: "fonctionner", sv: "fungera", ru: "работать / функционировать", it: "funzionare" },
  { cesky: "rozbít se", en: "break", de: "kaputtgehen", es: "romperse", nl: "kapotgaan", fr: "se casser", sv: "gå sönder", ru: "сломаться", it: "rompersi" },
  { cesky: "patřit", en: "belong", de: "gehören", es: "pertenecer", nl: "horen bij", fr: "appartenir", sv: "tillhöra", ru: "принадлежать", it: "appartenere" },
  { cesky: "chutnat", en: "taste", de: "schmecken", es: "gustar (comida)", nl: "smaken", fr: "avoir du goût", sv: "smaka", ru: "быть на вкус", it: "piacere (cibo)" },
  { cesky: "slušet (oblečení)", en: "suit / fit", de: "stehen / passen", es: "sentar bien", nl: "staan (kleding)", fr: "aller bien à", sv: "passa / klä", ru: "идти (об одежде)", it: "stare bene" },
  { cesky: "předcházet / dít se", en: "happen", de: "passieren", es: "pasar / ocurrir", nl: "gebeuren", fr: "se passer / arriver", sv: "hända", ru: "происходить / случаться", it: "succedere / accadere" },
  { cesky: "stát se (událost)", en: "happen / take place", de: "stattfinden", es: "tener lugar", nl: "plaatsvinden", fr: "avoir lieu", sv: "äga rum", ru: "состояться", it: "aver luogo" },
  { cesky: "pokračovat", en: "continue", de: "weitermachen / fortfahren", es: "continuar", nl: "doorgaan", fr: "continuer", sv: "fortsätta", ru: "продолжать", it: "continuare" },
  { cesky: "změnit", en: "change", de: "ändern", es: "cambiar", nl: "veranderen", fr: "changer", sv: "ändra", ru: "изменить / менять", it: "cambiare" },
  { cesky: "zlepšit", en: "improve", de: "verbessern", es: "mejorar", nl: "verbeteren", fr: "améliorer", sv: "förbättra", ru: "улучшить", it: "migliorare" },
  { cesky: "zhoršit", en: "worsen", de: "verschlechtern", es: "empeorar", nl: "verslechteren", fr: "aggraver / empirer", sv: "försämra", ru: "ухудшить", it: "peggiorare" },
  { cesky: "vyhrát", en: "win", de: "gewinnen", es: "ganar", nl: "winnen", fr: "gagner", sv: "vinna", ru: "выиграть", it: "vincere" },
  { cesky: "prohrát", en: "lose", de: "verlieren", es: "perder", nl: "verliezen", fr: "perdre", sv: "förlora", ru: "проиграть", it: "perdere" },
  { cesky: "používat", en: "use", de: "benutzen / verwenden", es: "usar", nl: "gebruiken", fr: "utiliser", sv: "använda", ru: "использовать", it: "usare / utilizzare" },
  { cesky: "zkusit / ochutnat", en: "try / taste", de: "probieren / versuchen", es: "probar / intentar", nl: "proberen", fr: "essayer / goûter", sv: "prova / försöka", ru: "пробовать / пытаться", it: "provare" },
  { cesky: "stihnout / dokázat", en: "manage / make it", de: "schaffen", es: "conseguir / lograr", nl: "halen / lukken", fr: "réussir / gérer", sv: "hinna / klara av", ru: "успеть / справиться", it: "riuscire / farcela" },
  { cesky: "vypnout (přístroj)", en: "turn off", de: "ausschalten", es: "apagar", nl: "uitschakelen / uitzetten", fr: "éteindre", sv: "stänga av", ru: "выключить", it: "spegnere" },
  { cesky: "zapnout (přístroj)", en: "turn on", de: "einschalten", es: "encender", nl: "inschakelen / aanzetten", fr: "allumer", sv: "sätta på", ru: "включить", it: "accendere" },
  { cesky: "stáhnout (z internetu)", en: "download", de: "herunterladen", es: "descargar", nl: "downloaden", fr: "télécharger", sv: "ladda ner", ru: "скачать", it: "scaricare" },
  { cesky: "poslat e-mail", en: "email", de: "mailen", es: "enviar un correo", nl: "mailen", fr: "envoyer un e-mail", sv: "mejla", ru: "отправить email", it: "inviare un'email" },
  { cesky: "kliknout", en: "click", de: "klicken", es: "hacer clic", nl: "klikken", fr: "cliquer", sv: "klicka", ru: "кликнуть / щелкнуть", it: "cliccare" },
  { cesky: "tvořit / stavět", en: "build / create", de: "bauen", es: "construir", nl: "bouwen", fr: "construire", sv: "bygga", ru: "строить", it: "costruire" },
  { cesky: "malovat", en: "paint", de: "malen", es: "pintar", nl: "schilderen", fr: "peindre", sv: "måla", ru: "красить / рисовать", it: "dipingere" },
  { cesky: "vytvořit", en: "create", de: "erstellen", es: "crear", nl: "maken / creëren", fr: "créer", sv: "skapa", ru: "создать", it: "creare" },
  { cesky: "trvat (časově)", en: "take time / last", de: "dauern", es: "durar", nl: "duren", fr: "durer", sv: "ta tid / vara", ru: "длиться / продолжаться", it: "durare" },
  { cesky: "zůstat stát / zastavit", en: "stop", de: "anhalten", es: "detenerse", nl: "stoppen / stilstaan", fr: "s'arrêter", sv: "stanna", ru: "остановиться", it: "fermarsi" },
  { cesky: "přejít / překročit", en: "cross", de: "überqueren", es: "cruzar", nl: "oversteken", fr: "traverser", sv: "korsa", ru: "перейти", it: "attraversare" },
  { cesky: "zatáhnout / odbočit", en: "turn", de: "abbiegen", es: "girar", nl: "afslaan", fr: "tourner", sv: "svänga", ru: "повернуть", it: "svoltare / girare" },
  { cesky: "pokračovat rovně", en: "go straight", de: "geradeaus gehen", es: "ir recto", nl: "rechtdoor gaan", fr: "aller tout droit", sv: "gå rakt fram", ru: "идти прямо", it: "andare diritto" },
  { cesky: "potkat", en: "meet / encounter", de: "begegnen", es: "encontrar", nl: "tegenkomen", fr: "rencontrer", sv: "möta", ru: "встретить", it: "incontrare" },
  { cesky: "pozdravit", en: "greet", de: "grüßen", es: "saludar", nl: "groeten", fr: "saluer", sv: "hälsa", ru: "поздороваться", it: "salutare" },
  { cesky: "rozloučit se", en: "say goodbye", de: "sich verabschieden", es: "despedirse", nl: "afscheid nemen", fr: "dire au revoir", sv: "säga adjö", ru: "попрощаться", it: "congedarsi" },
  { cesky: "blahopřát", en: "congratulate", de: "gratulieren", es: "felicitar", nl: "feliciteren", fr: "féliciter", sv: "gratulera", ru: "поздравлять", it: "congratularsi" },
  { cesky: "překvapit", en: "surprise", de: "überraschen", es: "sorprender", nl: "verrassen", fr: "surprendre", sv: "överraska", ru: "удивить / поразить", it: "sorprendere" },
  { cesky: "vylekat se", en: "be frightened", de: "erschrecken", es: "asustarse", nl: "schrikken", fr: "s'effrayer", sv: "bli skrämd", ru: "испугаться", it: "spaventarsi" },
  { cesky: "doufat", en: "hope", de: "hoffen", es: "esperar", nl: "hopen", fr: "espérer", sv: "hoppas", ru: "надеяться", it: "sperare" },
  { cesky: "zůstat zdravý", en: "stay healthy", de: "gesund bleiben", es: "mantenerse sano", nl: "gezond blijven", fr: "rester en bonne santé", sv: "hålla sig frisk", ru: "оставаться здоровым", it: "mantenersi in salute" },
  { cesky: "přibrat (na váze)", en: "gain weight", de: "zunehmen", es: "ganar peso", nl: "aankomen", fr: "prendre du poids", sv: "gå upp i vikt", ru: "поправиться / набрать вес", it: "ingrassare" },
  { cesky: "hubnout", en: "lose weight", de: "abnehmen", es: "perder peso", nl: "afvallen", fr: "perdre du poids", sv: "gå ner i vikt", ru: "худеть", it: "dimagrire" },
  { cesky: "kouřit", en: "smoke", de: "rauchen", es: "fumar", nl: "roken", fr: "fumer", sv: "röka", ru: "курить", it: "fumare" },
  { cesky: "vzdát se / přestat s", en: "give up", de: "aufgeben", es: "rendirse / dejar", nl: "opgeven", fr: "abandonner", sv: "ge upp", ru: "сдаться / бросить", it: "arrendersi" },
  { cesky: "stýskat se", en: "miss", de: "vermissen", es: "echar de menos", nl: "gemis / missen", fr: "manquer", sv: "sakna", ru: "скучать", it: "mancare" },
  { cesky: "pamatovat", en: "remember", de: "behalten", es: "recordar", nl: "onthouden", fr: "garder en mémoire", sv: "komma ihåg", ru: "помнить", it: "ricordare" },
  { cesky: "doprovodit", en: "accompany", de: "begleiten", es: "acompañar", nl: "begeleiden", fr: "accompagner", sv: "följa med", ru: "сопровождать", it: "accompagnare" },
  { cesky: "zazvonit", en: "ring", de: "klingeln", es: "sonar / llamar al timbre", nl: "bellen / klingelen", fr: "sonner", sv: "ringa", ru: "позвонить (в дверь/звонок)", it: "suonare" },
  { cesky: "ztratit se", en: "get lost", de: "verloren gehen", es: "perderse", nl: "verdwalen", fr: "se perdre", sv: "gå vilse", ru: "потеряться", it: "perdersi" },
  { cesky: "najít cestu", en: "find the way", de: "den Weg finden", es: "encontrar el camino", nl: "de weg vinden", fr: "trouver le chemin", sv: "hitta vägen", ru: "найти дорогу", it: "trovare la strada" }

]
};